partial/force-app/main/default/objects/File_Store__c/File_Store__c.object-meta.xml
<CustomObject>
    <label>File Store</label>
    <nameField>
        <displayFormat>FS#{0000000}</displayFormat>
        <label>File Store Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Store</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/File_Store__c/fields/FileExtension__c.field-meta.xml
<CustomField>
    <fullName>FileExtension__c</fullName>
    <label>FileExtension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/File_Store__c/fields/S3ServerUrl__c.field-meta.xml
<CustomField>
    <fullName>S3ServerUrl__c</fullName>
    <label>S3ServerUrl</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/classes/S3FileController.cls
public class S3FileController {
    @AuraEnabled
    public static string getFileUrl(string record)
    {
        try
        {
            List<File_Store__c> files=[SELECT  S3ServerUrl__c,FileExtension__c FROM File_Store__c 
                                      where Id=:record];
            File_Store__c file=files[0];
            return file.S3ServerUrl__c;
        }
        catch(Exception ex)
        {
            system.debug('ex:'+ex.getMessage());
            return '';
        }
    }
}