partial/force-app/main/default/objects/Account/fields/archivedOn__c.field-meta.xml
<CustomField>
    <fullName>archivedOn__c</fullName>
    <label>Archived On</label>
    <type>Date</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Country_Id__c.field-meta.xml
<CustomField>
    <fullName>Country_Id__c</fullName>
    <label>Country</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/ETag__c.field-meta.xml
<CustomField>
    <fullName>ETag__c</fullName>
    <label>ETag</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Identity_Check__c.field-meta.xml
<CustomField>
    <fullName>Identity_Check__c</fullName>
    <label>Identity Check</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Line_1__c.field-meta.xml
<CustomField>
    <fullName>Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Line_2__c.field-meta.xml
<CustomField>
    <fullName>Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Line_3__c.field-meta.xml
<CustomField>
    <fullName>Line_3__c</fullName>
    <label>Address Line 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Line_4__c.field-meta.xml
<CustomField>
    <fullName>Line_4__c</fullName>
    <label>Address Line 4</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/MarketingConsent__c.field-meta.xml
<CustomField>
    <fullName>MarketingConsent__c</fullName>
    <label>MarketingConsent</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/negotiatorId__c.field-meta.xml
<CustomField>
    <fullName>negotiatorId__c</fullName>
    <label>Negotiator Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/officeIds__c.field-meta.xml
<CustomField>
    <fullName>officeIds__c</fullName>
    <label>Office Ids</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Id__c</fullName>
    <label>Source Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Supplier_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Type_Id__c</fullName>
    <label>Supplier Type Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/TypeId__c.field-meta.xml
<CustomField>
    <fullName>TypeId__c</fullName>
    <label>Type Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Vat_Registered__c.field-meta.xml
<CustomField>
    <fullName>Vat_Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vat Registered</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>API#{0000000}</displayFormat>
        <label>API Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/API_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/API_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/Building_Number__c.field-meta.xml
<CustomField>
    <fullName>Building_Number__c</fullName>
    <label>Building Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/buildingName__c.field-meta.xml
<CustomField>
    <fullName>buildingName__c</fullName>
    <label>Building Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/Country_ID__c.field-meta.xml
<CustomField>
    <fullName>Country_ID__c</fullName>
    <label>Country ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/fromArchieve__c.field-meta.xml
<CustomField>
    <fullName>fromArchieve__c</fullName>
    <defaultValue>false</defaultValue>
    <label>From Archieve</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/line2__c.field-meta.xml
<CustomField>
    <fullName>line2__c</fullName>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/Reapit_ID__c.field-meta.xml
<CustomField>
    <fullName>Reapit_ID__c</fullName>
    <externalId>true</externalId>
    <label>Reapit ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Project_Unit_Type__c/Project_Unit_Type__c.object-meta.xml
<CustomObject>
    <label>Project Unit Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Unit Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/classes/Druce_ReapitContactHandler.cls
public class Druce_ReapitContactHandler {
    Public static void contactSync(String Contactstring){
        Druce_AccountContactDataWrapper requestWrapper = (Druce_AccountContactDataWrapper)JSON.deserialize(Contactstring, Druce_AccountContactDataWrapper.class); 
        List<Account> accountList = new List<Account>();
        List<Contact> contactList = new List<Contact>();
        if(requestWrapper.embedded != NULL){
            Druce_AccountContactDataWrapper.embedded exnewVar = requestWrapper.embedded;
            System.debug('id :'+requestWrapper.embedded.id);
            Account acc = new Account();
            Contact cont = new Contact ();
            // Check Reapit Id not exists in System then assign Unit Type
            /* List<Account> accList = [SELECT Id FROM Account WHERE Reapit_Id__c =: exnewVar.Id ]; 
if(unitList.isEmpty() ){
unit.Project_Unit_Type__c = 'a070T000003NSzSQAW';
}  
Druce_FetchVendorAccountDataWrapper.Account accWrap = new Druce_FetchVendorAccountDataWrapper.Account();
accWrap = exnewVar.Account; */
            
            
            cont.Title =  exnewVar.title;
            cont.Firstname = exnewVar.forename;
            cont.lastname = exnewVar.surname;
            cont.Birthdate = exnewVar.dateOfBirth;
            cont.IsActive__c = exnewVar.active; //checkbox
            cont.HomePhone = exnewVar.homePhone;
            cont.MobilePhone = exnewVar.mobilePhone;
            cont.Email = exnewVar.email;
            cont.fromArchieve__c =exnewVar.fromArchive; //checkbox
            //cont.Name = exnewVar
            //cont.Description = exnewVar
            cont.buildingName__c = exnewVar.primaryAddress.buildingName;
            cont.Building_Number__c = exnewVar.primaryAddress.buildingNumber;
            cont.Line_1__c = exnewVar.primaryAddress.line1;
            cont.line2__c = exnewVar.primaryAddress.line2;
            cont.Line_3__c = exnewVar.primaryAddress.line3;
            cont.Line_4__c = exnewVar.primaryAddress.line4;
            cont.Postcode__c = exnewVar.primaryAddress.postcode;
            cont.Country__c = exnewVar.primaryAddress.countryId;
            
            
            
            acc.PersonTitle = exnewVar.title;
            acc.Firstname = exnewVar.forename;
            acc.lastname = exnewVar.surname;
            acc.PersonBirthdate = exnewVar.dateOfBirth;
            acc.IsActive__c = exnewVar.active;
            acc.MarketingConsent__c = exnewVar.marketingConsent;
            acc.Identity_Check__c = exnewVar.identityCheck;
            acc.Source_Id__c = exnewVar.source;
            acc.Phone = exnewVar.mobilePhone;
            acc.Email__c = exnewVar.email;
            acc.archivedOn__c = exnewVar.archivedOn;
            acc.fromArchieve__pc = exnewVar.fromArchive;
            acc.officeIds__c = String.valueOf(exnewVar.officeIds);           
            acc.negotiatorId__c = String.valueOf(exnewVar.negotiatorIds);   
            acc.CommunicationPreferenceLetter__pc = exnewVar.communicationPreferenceLetter;
            acc.CommunicationPreferenceEmail__pc = exnewVar.communicationPreferenceEmail;
            acc.CommunicationPreferencePhone__pc = exnewVar.communicationPreferencePhone;
            acc.CommunicationPreferenceSMS__pc = exnewVar.communicationPreferenceSMS;
            //acc.ETag__c = exnewVar
            //acc.Name = exnewVar
            //acc.Branch__c = exnewVar
            //acc.Notes__c = exnewVar
            //acc.Vat_Registered__c = exnewVar
            //acc.TypeId__c = exnewVar
            //acc.Supplier_Type_Id__c = exnewVar
            acc.Line_1__c = exnewVar.primaryAddress.line1;
            acc.Line_2__c = exnewVar.primaryAddress.line2;
            acc.Line_3__c = exnewVar.primaryAddress.line3;
            acc.Line_4__c = exnewVar.primaryAddress.line4;
            acc.Postcode__c = exnewVar.primaryAddress.postcode;
            acc.Country_Id__c = exnewVar.primaryAddress.countryId;
            
            contactList.add(Cont);
            accountList.add(acc); 
         }
        upsert accountList;
        upsert contactList;
        API_Log__c apiLog = new API_Log__c();
            apiLog.Method__c = 'POST';
            apiLog.Object_Name__c = 'Account';        
            apiLog.Request_Body__c = Contactstring;
            //apiLog.Response_Body__c = responseString;
            insert apiLog;
        
        Druce_ReapitResponse.response response = new Druce_ReapitResponse.response();
        Druce_ReapitResponse resWrapper = new Druce_ReapitResponse();
        List<Druce_ReapitResponse.results> resultList = new List<Druce_ReapitResponse.results>();
        Druce_ReapitResponse.results result = new Druce_ReapitResponse.results();
        result.message = 'Account & Contact successfully published into salesforce';
        resultList.add(result);
        response.results = resultList;
        response.Status = 'Success';
        response.status_code = '200';
        
        resWrapper.response = response;
        system.debug('---->');
        
        
    }
}