partial/force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Building_Name__c.field-meta.xml
<CustomField>
    <fullName>Building_Name__c</fullName>
    <label>Building Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Country_Id__c.field-meta.xml
<CustomField>
    <fullName>Country_Id__c</fullName>
    <label>Country</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/ETag__c.field-meta.xml
<CustomField>
    <fullName>ETag__c</fullName>
    <label>ETag</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Line_1__c.field-meta.xml
<CustomField>
    <fullName>Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Line_2__c.field-meta.xml
<CustomField>
    <fullName>Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Line_3__c.field-meta.xml
<CustomField>
    <fullName>Line_3__c</fullName>
    <label>Address Line 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Line_4__c.field-meta.xml
<CustomField>
    <fullName>Line_4__c</fullName>
    <label>Address Line 4</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/MarketingConsent__c.field-meta.xml
<CustomField>
    <fullName>MarketingConsent__c</fullName>
    <label>MarketingConsent</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/negotiatorId__c.field-meta.xml
<CustomField>
    <fullName>negotiatorId__c</fullName>
    <label>Negotiator Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/officeIds__c.field-meta.xml
<CustomField>
    <fullName>officeIds__c</fullName>
    <label>Office Ids</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Portal_Account__c.field-meta.xml
<CustomField>
    <fullName>Portal_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal Account</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Reapit_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Reapit_Created_Date__c</fullName>
    <label>Reapit Created Date</label>
    <type>DateTime</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Reapit_Id_Calc__c.field-meta.xml
<CustomField>
    <fullName>Reapit_Id_Calc__c</fullName>
    <externalId>true</externalId>
    <label>Reapit Id Calc</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Reapit_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>Reapit_Modified_Date__c</fullName>
    <label>Reapit Modified Date</label>
    <type>DateTime</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Supplier_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Type_Id__c</fullName>
    <label>Supplier Type Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/TypeId__c.field-meta.xml
<CustomField>
    <fullName>TypeId__c</fullName>
    <label>Type Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Vat_Registered__c.field-meta.xml
<CustomField>
    <fullName>Vat_Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vat Registered</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/Building_Number__c.field-meta.xml
<CustomField>
    <fullName>Building_Number__c</fullName>
    <label>Building Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/buildingName__c.field-meta.xml
<CustomField>
    <fullName>buildingName__c</fullName>
    <label>Building Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/Country_ID__c.field-meta.xml
<CustomField>
    <fullName>Country_ID__c</fullName>
    <label>Country ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/line2__c.field-meta.xml
<CustomField>
    <fullName>line2__c</fullName>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/Portal_Contact__c.field-meta.xml
<CustomField>
    <fullName>Portal_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal Contact</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/Reapit_ID__c.field-meta.xml
<CustomField>
    <fullName>Reapit_ID__c</fullName>
    <externalId>true</externalId>
    <label>Reapit ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/classes/Druce_FetchCompanyAPI.cls
global class Druce_FetchCompanyAPI implements Queueable, Database.AllowsCallouts {
    public Integer pageNo = 1;
    public String httpresponse;
    public String reqpathUrl;
    public String url;
    
    public Druce_FetchCompanyAPI(Integer pageNo)
    {
        this.pageNo = pageNo;
    }
    public void execute(QueueableContext context) {
        try{
            Http h = new Http();
            HttpRequest request = new HttpRequest();
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            String path = '?client_id=3ohfvftvn15aap62di1nksaglu&grant_type=client_credentials';
            request.setEndpoint('callout:Reapit_API');
            String payLoad = 'client_id=3ohfvftvn15aap62di1nksaglu&grant_type=client_credentials';
            request.setBody(payLoad);
            request.setTimeout(60000);
            HttpResponse response = h.send(request);
            system.debug('Response Auth ::'+response);
            if(response.getStatusCode() == 200){
                system.debug('response body :'+response.getBody());
                Druce_FetchVendorAccountAPI.wrapperAuth wrap = new Druce_FetchVendorAccountAPI.wrapperAuth();
                
                wrapperAuth ex = (wrapperAuth)JSON.deserialize(response.getBody(), wrapperAuth.class);
                system.debug(':::'+ex.access_token);
                Http http = new Http();
                HttpRequest requestnew = new HttpRequest();
                reqpathUrl = '/companies?pagesize=25&pageNumber='+pageNo;  //'/companies/CSO230287';
                //reqpathUrl = '/companies?pagenumber=1&pagesize=2&id=KOF230040';  //'/companies/CSO230287';
                requestnew.setMethod('GET');
                requestnew.setEndpoint('callout:Reapit_Properties'+reqpathUrl);
                requestnew.setHeader('Content-Type','application/json');
                requestnew.setHeader('Authorization','Bearer '+ex.access_token);
                requestnew.setHeader('reapit-customer', 'URA');
                requestnew.setHeader('api-version','2023-01-17');
                requestnew.setTimeout(100000);
                HttpResponse responseNew = http.send(requestnew);
                httpresponse = responseNew.getBody();
                
                if(responseNew.getStatusCode() == 200){
                    string rs = responseNew.getBody();
                    rs = rs.replaceAll('_embedded','embedded');
                    rs = rs.replace('_eTag', 'eTag');
                    rs = rs.replace('_links', 'links');
                    
                    system.debug('Response Body ::'+rs);
                    Druce_FetchCompanyAPIWrapper exnew = (Druce_FetchCompanyAPIWrapper)JSON.deserialize(rs, Druce_FetchCompanyAPIWrapper.class);
                    system.debug('Wrapper :: '+exnew);
                    List<Account> AccountList = new List<Account>();
                    List<Contact> ContactList = new List<Contact>();
                    Map<String, Account> mapAccounts = new Map<String, Account>();
                    for(Druce_FetchCompanyAPIWrapper.Company exnewVar : exnew.embedded){
                        system.debug('---->'+exnewVar.id);
                        Account Account = new Account();
                        Contact Contact = new Contact();
                        
                        Account.Reapit_ID__c = exnewVar.id;
                        Account.Portal_Account__c = TRUE;
                        Account.RecordTypeId = Druce_Constants.CorpAccount;
                        //Account.Reapit_Id_Calc__c = exnewVar.id+'_'+relatedWrapper.id;
                        Account.Reapit_Created_Date__c = exnewVar.created;
                        Account.Reapit_Modified_Date__c = exnewVar.modified;
                        Account.Name = exnewVar.name;
                        Account.Branch__c = exnewVar.branch;
                        Account.Notes__c = exnewVar.notes;
                        Account.IsActive__c = exnewVar.active;
                        Account.MarketingConsent__c = exnewVar.marketingConsent;
                        Account.Vat_Registered__c = exnewVar.vatRegistered;
                        String typeId = '';
                        if(exnewVar.typeIds.size() > 0){
                            for(string s : exnewVar.typeIds){
                                typeId = s + ' ' + typeId;
                            }
                        }
                        Account.TypeId__c = typeId;
                        Account.Supplier_Type_Id__c = exnewVar.supplierTypeId;
                        Account.Email__c = exnewVar.email;
                        
                        if(exnewVar.officeIds.size() > 0){
                            Account.officeIds__c = exnewVar.officeIds[0];
                        }
                        if(exnewVar.negotiatorIds.size() > 0){
                            Account.negotiatorId__c = exnewVar.negotiatorIds[0];
                        }
                        Account.ETag__c = exnewVar.eTag;
                        
                        
                        Contact.Reapit_ID__c = exnewVar.Id;
                        Contact.FirstName = exnewVar.name;
                        Contact.LastName = '.';
                        Contact.MobilePhone = exnewVar.mobilePhone;
                        Contact.OtherPhone = exnewVar.workPhone;
                        Contact.Email = exnewVar.email;
                        for(Druce_FetchCompanyAPIWrapper.ContactDetail  additionalDetails: exnewVar.additionalContactDetails)
                        {
                            Account.Phone = additionalDetails.value;
                            Contact.Phone = additionalDetails.value;
                            Contact.Type__c = additionalDetails.type;
                        }
                        
                        Contact.buildingName__c = exnewVar.address.buildingName;
                        Contact.Building_Number__c = exnewVar.address.buildingNumber;
                        Contact.Line_1__c = exnewVar.address.line1;
                        Contact.line2__c = exnewVar.address.line2;
                        Contact.Line_3__c = exnewVar.address.line3;
                        Contact.Line_4__c = exnewVar.address.line4;
                        Contact.Postcode__c = exnewVar.address.postcode;
                        Contact.Country_ID__c = exnewVar.address.country;
                        
                        Account.Building_Name__c = exnewVar.address.buildingName;
                        Account.Building_Number__c = exnewVar.address.buildingNumber;
                        Account.Line_1__c = exnewVar.address.line1;
                        Account.Line_2__c = exnewVar.address.line2;
                        Account.Line_3__c = exnewVar.address.line3;
                        Account.Line_4__c = exnewVar.address.line4;
                        Account.Postcode__c = exnewVar.address.postcode;
                        Account.Country_Id__c = exnewVar.address.country;
                        //Contact.Portal_Contact__c = TRUE;
                        
                        AccountList.add(Account);
                        ContactList.add(Contact);
                        
                    }
                    
                    upsert AccountList Reapit_Id__c;
                    Map<string,Account> AccMap = new Map<string,Account>();
                    for(Account acc : AccountList){
                        if(acc.Reapit_Id__c != NULL){
                            AccMap.put(acc.Reapit_Id__c,acc);
                        }
                    }
                    
                    for(Contact con: ContactList){
                        if(AccMap.containsKey(con.Reapit_ID__c)){
                            con.AccountId = AccMap.get(con.Reapit_ID__c).Id;
                        }
                    }
                    upsert ContactList Reapit_ID__c;
                    
                }
                else{system.debug('---->Failed');}
            }
        }
        catch(Exception e){
            system.debug('Exception '+e.getMessage()); 
            system.debug('Line Number '+e.getLineNumber()); 
        }
    }
    
    public class wrapperAuth {
        public String access_token;
        public Integer expire_in;
        public string token_type;
    }
}