partial/force-app/main/default/objects/Account/fields/Country_Id__c.field-meta.xml
<CustomField>
    <fullName>Country_Id__c</fullName>
    <label>Country</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/DXF_SF_Prop_ID__c.field-meta.xml
<CustomField>
    <fullName>DXF_SF_Prop_ID__c</fullName>
    <label>DXF_SF_Prop_ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Line_1__c.field-meta.xml
<CustomField>
    <fullName>Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/CEARegistrationNo__c.field-meta.xml
<CustomField>
    <fullName>CEARegistrationNo__c</fullName>
    <label>CEA Registration No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/CompanyReferral__c.field-meta.xml
<CustomField>
    <fullName>CompanyReferral__c</fullName>
    <description>Referrer&apos;s Company Information</description>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/ContactReferral__c.field-meta.xml
<CustomField>
    <fullName>ContactReferral__c</fullName>
    <label>Contact</label>
    <type>Phone</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/DXF_Ext_User_ID__c.field-meta.xml
<CustomField>
    <fullName>DXF_Ext_User_ID__c</fullName>
    <description>To capture the External System User Id</description>
    <label>DXF_Ext_User_ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/DXF_SF_Prop_ID__c.field-meta.xml
<CustomField>
    <fullName>DXF_SF_Prop_ID__c</fullName>
    <description>Sfdc Property Id</description>
    <label>DXF_SF_Prop_ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/DXF_SF_Unit_ID__c.field-meta.xml
<CustomField>
    <fullName>DXF_SF_Unit_ID__c</fullName>
    <label>DXF SF Unit Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/EmailReferral__c.field-meta.xml
<CustomField>
    <fullName>EmailReferral__c</fullName>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/Fly_in_Program__c.field-meta.xml
<CustomField>
    <fullName>Fly_in_Program__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fly in Program</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Non-Specific</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/Lead_DB_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_DB_Id__c</fullName>
    <label>Web_Lead_Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buying</fullName>
            </value>
            <value>
                <fullName>Selling</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Letting</fullName>
            </value>
            <value>
                <fullName>Valuation</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>User Registration</fullName>
            </value>
            <value>
                <fullName>Instant Valuation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/MarketsInterestedIn__c.field-meta.xml
<CustomField>
    <fullName>MarketsInterestedIn__c</fullName>
    <label>Markets Interested In</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/NameReferral__c.field-meta.xml
<CustomField>
    <fullName>NameReferral__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/Property_Interested__c.field-meta.xml
<CustomField>
    <fullName>Property_Interested__c</fullName>
    <description>Created to capture the Properties Interested In which Area</description>
    <label>Property Interested</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Project_Id__c</fullName>
    <label>Project Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Unit_Id__c.field-meta.xml
<CustomField>
    <fullName>Unit_Id__c</fullName>
    <label>Unit Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/recordTypes/Buying.recordType-meta.xml
<RecordType>
    <fullName>Buying</fullName>
    <active>true</active>
    <businessProcess>Buying Process</businessProcess>
    <label>Buying UK</label>
</RecordType>

partial/force-app/main/default/objects/Opportunity/recordTypes/Tenancy.recordType-meta.xml
<RecordType>
    <fullName>Tenancy</fullName>
    <active>true</active>
    <businessProcess>Tenancy Process</businessProcess>
    <label>Tenancy UK</label>
</RecordType>

partial/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Primary Property</label>
</RecordType>

partial/force-app/main/default/objects/Project_Unit_Type__c/Project_Unit_Type__c.object-meta.xml
<CustomObject>
    <label>Project Unit Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Unit Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project_Unit_Type__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Unit Types</relationshipLabel>
    <relationshipName>Project_Unit_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit__c/fields/Project_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Unit_Type__c</fullName>
    <label>Project Unit Type</label>
    <referenceTo>Project_Unit_Type__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/View_Interest__c.object-meta.xml
<CustomObject>
    <label>View Interest</label>
    <nameField>
        <label>View Interest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>View Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/View_Interest__c/fields/DXF_Ext_User_ID__c.field-meta.xml
<CustomField>
    <fullName>DXF_Ext_User_ID__c</fullName>
    <label>DXF_Ext_User_ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/DXF_SF_Prop_ID__c.field-meta.xml
<CustomField>
    <fullName>DXF_SF_Prop_ID__c</fullName>
    <label>DXF_SF_Prop_ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/DXF_SF_Unit_Id__c.field-meta.xml
<CustomField>
    <fullName>DXF_SF_Unit_Id__c</fullName>
    <label>DXF_SF_Unit_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>View Interests</relationshipLabel>
    <relationshipName>View_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Lead_DB_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_DB_Id__c</fullName>
    <description>This fields has been created to capture the External Id</description>
    <label>Web_Lead_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Property_Interested__c.field-meta.xml
<CustomField>
    <fullName>Property_Interested__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Interested</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>View Interests</relationshipLabel>
    <relationshipName>View_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Unit_Interested__c.field-meta.xml
<CustomField>
    <fullName>Unit_Interested__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Interested</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>View Interests</relationshipLabel>
    <relationshipName>View_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/classes/LeadRestService.cls
@RestResource(urlMapping='/leads__test/*')
global class LeadRestService {
    
    /**********************Monika: Lead API - Get: 0/01/2023**********************************/
    
    @HttpGet
    global Static List<Lead> getLead(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String recId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        List<Lead> leadResult;
        system.debug('recId :'+recId);
        
        if(String.isNotBlank(recId)){
            leadResult = [SELECT Id, LastName, FirstName,Email,phone,Lead_DB_Id__c
                          FROM Lead WHERE Id = :recId];
        }     
        return leadResult;    
    }
    /**********************Monika: Lead API - Get End: 0/01/2023**********************************/
    
    @HttpPost
    global Static void createLead(){
        
        String strJSON;
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        string jsonString = req.requestBody.tostring();
        system.debug('jsonString : '+jsonString);
        
        boolean successCheck;
        
        DXF_ResponseWrapper resWrapper = new DXF_ResponseWrapper();
        DXF_ResponseWrapper.response response = new DXF_ResponseWrapper.response();
        List<DXF_ResponseWrapper.results> resultList = new List<DXF_ResponseWrapper.results>();
        
        List<DXF_LeadRequestWrapper> wRespList = (List<DXF_LeadRequestWrapper>) JSON.deserialize(jsonString, List<DXF_LeadRequestWrapper>.class);
        
        List<Lead> leadList = new List<Lead>();
        List<Account> accountList = new List<Account>();
        List<View_Interest__c> lstViewInterest = new List<View_Interest__c>();
        List<Opportunity> NewOpp = new List<Opportunity>();
        
        for(DXF_LeadRequestWrapper wResp: wRespList){
            if(String.isNOtBlank(wResp.sf_Prop_Id) || String.isNOtBlank(wResp.sf_Unit_Id)){
                List<Account> checkExistingLeads = [SELECT Id, Phone, Name, PersonEmail FROM Account WHERE PersonEmail =: wResp.email AND Phone =: wResp.phone];
                if(!checkExistingLeads.isEmpty()){
                    
                    Opportunity opp = new Opportunity();
                   //opp.Lead__c = checkExistingLeads[0].Id;
                    if (wResp.lead_type == 'Buying')
                    {opp.RecordTypeId =Druce_Constants.Oppourtnitybuying;}
                    else if (wResp.lead_type == 'Selling')
                        {opp.RecordTypeId =Druce_Constants.Oppourtnityselling;}
                    else if (wResp.lead_type == 'Letting')
                        {opp.RecordTypeId =Druce_Constants.OppourtnityLetting;}
                    else if (wResp.lead_type == 'Tenancy')
                        {opp.RecordTypeId =Druce_Constants.OppourtnityTenancy;}
                        
   
		             opp.AccountId = checkExistingLeads[0].Id;
		             opp.StageName = 'Indicated Interest';
		             opp.CloseDate = System.today().addDays(10);
                   
                    //Account accountname = [SELECT Id,Name FROM Account WHERE Id =:wResp.user_Id];
					
					
                    if(String.isNOtBlank(wResp.sf_Prop_Id)){
                        opp.Project_Id__c = wResp.sf_Prop_Id;
                        /*Project__c project = [SELECT Id,Name FROM Project__c WHERE Id =:wResp.sf_Prop_Id];
                        vi.Property_Interested__c = project.Id;
                        vi.Name = wResp.lastName + ' Interest '+project.Name;*/
                    }
                    
                    if(String.isNOtBlank(wResp.sf_Unit_Id)){
                        opp.Unit_Id__c = wResp.sf_Unit_Id;
                        UNIT__c unit = [SELECT Id,Name FROM UNIT__c WHERE Id =:wResp.sf_Unit_Id];
                        //vi.Unit_Interested__c = unit.Id;
                        //vi.Name = wResp.lastName + ' Interest '+unit.Name;
						//String UnitTypeId = [SELECT Project_Unit_Type__c FROM UNIT__c WHERE Id = :wResp.sf_Unit_Id LIMIT 1].Project_Unit_Type__c;
                        Unit__c UnitType =  [select Project_Unit_Type__c , Project_Unit_Type__r.project__c FROM UNIT__c WHERE Id = :wResp.sf_Unit_Id];
                        
                        
                        opp.Project_Id__c = UnitType.Project_Unit_Type__r.project__c; 
                    }
                    UNIT__c unit = [SELECT Id,Name FROM UNIT__c WHERE Id =:wResp.sf_Unit_Id];
					opp.Name = checkExistingLeads[0].Name + unit.Name;
                    NewOpp.add(opp);
                }
            }else{
                
             	List<Lead> Leads = [SELECT Id, Phone, Email FROM Lead WHERE Email =: wResp.email AND Phone =: wResp.phone];   
                if(!Leads.isEmpty()){
                    DXF_ResponseWrapper.results result = new DXF_ResponseWrapper.results();
                    
                    result.message = 'Lead details already exists in system.';
                    resultList.add(result);
                    
                    response.results = resultList;
                    response.Status = 'Failed';
                    response.status_code = '400';
                    resWrapper.response = response;
                    strJSON = JSON.serialize(resWrapper);
                    
                    RestContext.response.addHeader('Content-Type', 'application/json');
                    RestContext.response.responseBody = Blob.valueOf(strJSON);
                    
                }else{
                	Lead obj = new Lead();
                    Account acc = new Account();
                    obj.salutation = wResp.salutation;
                    obj.LastName = wResp.lastName;
                    obj.FirstName = wResp.firstName;
                    obj.Email = wResp.email;
                    obj.Phone = wResp.phone;
                    obj.Gender__c = wResp.gender;
                    obj.Language__c = wResp.language;
                    obj.Lead_Type__c = wResp.lead_type;
                    obj.Industry = wResp.industry;
                    obj.Title = wResp.title;
                    obj.Company = wResp.company;
                    obj.NumberOfEmployees = wResp.noofEmployees == NULL ? NULL : Integer.valueOf(wResp.noofEmployees);
                    obj.Rating = wResp.rating;
                    if(wResp.fly_In_Program != NULL){
                        obj.Fly_in_Program__c = wResp.fly_In_Program;
                    }
                    if(wResp.donotCall != NULL){
                        obj.DoNotCall = wResp.donotCall;                
                    }
                    if(wResp.emailOptOut != NULL){
                        obj.HasOptedOutOfEmail = wResp.emailOptOut;
                    }
                    
                    obj.MobilePhone = wResp.mobile;                
                    obj.MarketsInterestedIn__c = wResp.markets_Interested_In;
                    /*obj.CEARegistrationNo__c = wResp.referrer_CEA_RegNo;
                    obj.EmailReferral__c = wResp.referrer_Email;
                    obj.ContactReferral__c = wResp.referrer_Contact;
                    obj.CompanyReferral__c = wResp.referrer_Company;
                    obj.NameReferral__c = wResp.referrer_Name;*/
                    obj.Lead_DB_Id__c = wResp.Lead_DB_Id;
                    obj.street = wResp.street;
                    obj.city = wResp.city;
                    obj.state = wResp.state;
                    obj.country = wResp.country;
                    obj.postalCode = wResp.postalCode;
                    obj.DXF_Ext_User_Id__c = wResp.user_Id;
                    obj.DXF_SF_Prop_ID__c = wResp.sf_Prop_Id;
                    obj.DXF_SF_Unit_Id__c = wResp.sf_Unit_Id;
                    obj.Description = wResp.description;
                    leadList.add(obj);
                    
                    acc.lastname = wResp.lastName;
                    acc.FirstName = wResp.firstName;
                    acc.Salutation = wResp.salutation;
                    acc.IsActive__c = TRUE;
                    acc.PersonEmail = wResp.email;
                    acc.Phone = wResp.phone;
                    if(wResp.emailOptOut != NULL){
                        acc.PersonHasOptedOutOfEmail = wResp.emailOptOut;
                    }
                    acc.Gender__pc = wResp.gender;
                    acc.Rating = wResp.rating;
                    acc.Line_1__c = wResp.street;
                    acc.Country_Id__c = wResp.country;
                    acc.Postcode__c = wResp.postalCode;
                    acc.BillingStreet = wResp.street;
                    acc.BillingCity = wResp.city;
                    acc.BillingState = wResp.state;
                    acc.BillingCountry = wResp.country;
                    acc.BillingPostalCode = wResp.postalCode;
                    acc.Description = wResp.description;
                    accountList.add(acc);    
                }            	
            }            
        }
        
        try{
            if(leadList.size() > 0){
                insert leadList;
                
                insert accountList;
                Map<String, Account> mapAcc = new Map<String,Account>();
                for(Account a : accountList){
                    mapAcc.put(a.PersonEmail+''+a.Phone, a);
                }
                
                successCheck = true;     
                for(Lead ld : leadList){
                    DXF_ResponseWrapper.results result = new DXF_ResponseWrapper.results();
                    result.extDB_Id = ld.Lead_DB_Id__c;
                    result.salesforce_Id = ld.Id;
                    if(mapAcc.containsKey(ld.Email+''+ld.Phone)){
                        result.userId = mapAcc.get(ld.Email+''+ld.Phone).Id;
                    }
                    result.message = 'User Created successfully';
                    resultList.add(result);
                }                
                
                response.results = resultList;
                response.Status = 'Success';
                response.status_code = '200';
                resWrapper.response = response;
                strJSON = JSON.serialize(resWrapper);
                
                RestContext.response.addHeader('Content-Type', 'application/json');
                RestContext.response.responseBody = Blob.valueOf(strJSON);
            }
            if(!lstViewInterest.isEmpty()){
                Insert lstViewInterest;
                successCheck = true;     
                for(View_Interest__c vi :lstViewInterest){
                    DXF_ResponseWrapper.results result = new DXF_ResponseWrapper.results();
                    result.extDB_Id = vi.External_Id__c;
                    result.salesforce_Id = vi.Id;
                    result.message = 'Interest Created successfully';
                    resultList.add(result);
                }                
                
                response.results = resultList;
                response.Status = 'Success';
                response.status_code = '200';
                resWrapper.response = response;
                strJSON = JSON.serialize(resWrapper);
                
                RestContext.response.addHeader('Content-Type', 'application/json');
                RestContext.response.responseBody = Blob.valueOf(strJSON);
            }
        }
        
        catch(DmlException e){
            successCheck = false;
            Integer numErrors = e.getNumDml();
            String errormessage ='Error: ';
            for(Integer i=0;i<numErrors;i++) {
                errormessage = errormessage + e.getDmlMessage(i);
            }
            
            if(errormessage.contains('Use one of these records')){
                response.errormessage = 'Lead details already exists in system.';
            }else{
            	response.errormessage = errormessage + '; No. of Error: ' + numErrors;    
            }
            response.Status = 'Error';
            response.status_code = '400';
            resWrapper.response = response;
            strJSON = JSON.serialize(resWrapper);
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(strJSON);
        }
        catch(Exception e){
            successCheck = false;       
            response.errormessage = e.getMessage();
            response.Status = 'Failed';
            response.status_code = 'Err_Excep';
            resWrapper.response = response;
            strJSON = JSON.serialize(resWrapper);
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(strJSON);
        }
    }
    
    /**********************Monika: Lead API - Post End:**********************************/
    
    @HttpPUT
    global Static void updateLead(){
        
        String strJSON;
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        string jsonString = req.requestBody.tostring();
        system.debug('jsonString : '+jsonString);
        
        boolean successCheck;
        List<DXF_LeadRequestWrapper> wRespList = (List<DXF_LeadRequestWrapper>) JSON.deserialize(jsonString,List<DXF_LeadRequestWrapper>.class);
        
        List<Lead> leadList = new List<Lead>();
        
        for(DXF_LeadRequestWrapper wResp: wRespList){
            Lead obj = new Lead();
            obj.LastName = wResp.LastName;   
            obj.FirstName = wResp.FirstName;    
            obj.Email = wResp.Email;   
            obj.Phone = wResp.phone;
            obj.Id = wResp.Lead_SF_Id;
            // obj.Status = wResp.leadStatus;
            obj.Lead_DB_Id__c = wResp.Lead_DB_Id;
            leadList.add(obj);
        }
        DXF_ResponseWrapper resWrapper = new DXF_ResponseWrapper();
        DXF_ResponseWrapper.response response = new DXF_ResponseWrapper.response();
        List<DXF_ResponseWrapper.results> resultList = new List<DXF_ResponseWrapper.results>();
        try{
            if(leadList.size() > 0){
                update leadList;
                successCheck = true;
                
                for(Lead ld :leadList){
                    DXF_ResponseWrapper.results result = new DXF_ResponseWrapper.results();
                    result.extDB_Id = ld.Lead_DB_Id__c;
                    result.salesforce_Id = ld.Id;
                    resultList.add(result);
                }
                response.results = resultList;
                response.Status = 'Success';
                response.status_code = '200';
                resWrapper.response = response;
                strJSON = JSON.serialize(resWrapper);    
                RestContext.response.addHeader('Content-Type', 'application/json');
                RestContext.response.responseBody = Blob.valueOf(strJSON);
            }
        }
        
        catch(Exception e){
            successCheck = false;
        }
    }
    
    /**********************Monika: Lead API - Put End: **********************************/
}