partial/force-app/main/default/objects/Account/fields/Country_Id__c.field-meta.xml
<CustomField>
    <fullName>Country_Id__c</fullName>
    <label>Country</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/DXF_SF_Prop_ID__c.field-meta.xml
<CustomField>
    <fullName>DXF_SF_Prop_ID__c</fullName>
    <label>DXF_SF_Prop_ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Line_1__c.field-meta.xml
<CustomField>
    <fullName>Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Line_3__c.field-meta.xml
<CustomField>
    <fullName>Line_3__c</fullName>
    <label>Address Line 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/officeIds__c.field-meta.xml
<CustomField>
    <fullName>officeIds__c</fullName>
    <label>Office Ids</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Account/fields/Portal_Account__c.field-meta.xml
<CustomField>
    <fullName>Portal_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal Account</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/Building_Number__c.field-meta.xml
<CustomField>
    <fullName>Building_Number__c</fullName>
    <label>Building Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/buildingName__c.field-meta.xml
<CustomField>
    <fullName>buildingName__c</fullName>
    <label>Building Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/Country_ID__c.field-meta.xml
<CustomField>
    <fullName>Country_ID__c</fullName>
    <label>Country ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-Specific</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/line2__c.field-meta.xml
<CustomField>
    <fullName>line2__c</fullName>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/Portal_Contact__c.field-meta.xml
<CustomField>
    <fullName>Portal_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal Contact</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/DXF_SF_Prop_ID__c.field-meta.xml
<CustomField>
    <fullName>DXF_SF_Prop_ID__c</fullName>
    <description>Sfdc Property Id</description>
    <label>DXF_SF_Prop_ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/DXF_SF_Unit_ID__c.field-meta.xml
<CustomField>
    <fullName>DXF_SF_Unit_ID__c</fullName>
    <label>DXF SF Unit Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/Fly_in_Program__c.field-meta.xml
<CustomField>
    <fullName>Fly_in_Program__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fly in Program</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Non-Specific</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/Lead_DB_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_DB_Id__c</fullName>
    <label>Web_Lead_Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buying</fullName>
            </value>
            <value>
                <fullName>Selling</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Letting</fullName>
            </value>
            <value>
                <fullName>Valuation</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>User Registration</fullName>
            </value>
            <value>
                <fullName>Instant Valuation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/Office_ID__c.field-meta.xml
<CustomField>
    <fullName>Office_ID__c</fullName>
    <label>Office ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/Portal_Lead__c.field-meta.xml
<CustomField>
    <fullName>Portal_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal Lead</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/BuildingName__c.field-meta.xml
<CustomField>
    <fullName>BuildingName__c</fullName>
    <label>BuildingName old</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Office_ID__c.field-meta.xml
<CustomField>
    <fullName>Office_ID__c</fullName>
    <label>Office ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Project_Id__c</fullName>
    <label>Project Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Unit_Id__c.field-meta.xml
<CustomField>
    <fullName>Unit_Id__c</fullName>
    <label>Unit Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/recordTypes/Buying.recordType-meta.xml
<RecordType>
    <fullName>Buying</fullName>
    <active>true</active>
    <businessProcess>Buying Process</businessProcess>
    <label>Buying UK</label>
</RecordType>

partial/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project_Unit_Type__c/Project_Unit_Type__c.object-meta.xml
<CustomObject>
    <label>Project Unit Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Unit Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project_Unit_Type__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Unit Types</relationshipLabel>
    <relationshipName>Project_Unit_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit__c/fields/BuildingName__c.field-meta.xml
<CustomField>
    <fullName>BuildingName__c</fullName>
    <label>Building Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/Project_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Unit_Type__c</fullName>
    <label>Project Unit Type</label>
    <referenceTo>Project_Unit_Type__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Bungalow</fullName>
            </value>
            <value>
                <fullName>FlatApartment</fullName>
            </value>
            <value>
                <fullName>Maisonette</fullName>
            </value>
            <value>
                <fullName>Land</fullName>
            </value>
            <value>
                <fullName>Farm</fullName>
            </value>
            <value>
                <fullName>Cottage</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
            <value>
                <fullName>DevelopmentPlot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/classes/LeadRestService_adarsh.cls
@RestResource(urlMapping='/leads_olfd/*')
global class LeadRestService_adarsh {
    
    /**********************Monika: Lead API - Get: 0/01/2023**********************************/
    
    @HttpGet
    global Static List<Lead> getLead(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String recId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        List<Lead> leadResult;
        system.debug('recId :'+recId);
        
        if(String.isNotBlank(recId)){
            leadResult = [SELECT Id, LastName, FirstName,Email,phone,Lead_DB_Id__c
                          FROM Lead WHERE Id = :recId];
        }     
        return leadResult;    
    }
    /**********************Monika: Lead API - Get End: 0/01/2023**********************************/
    
    @HttpPost
    global Static void createLead(){
        
        String strJSON;
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        string jsonString = req.requestBody.tostring();
        
        boolean successCheck;
        List<Lead> leadList = new List<Lead>();
        List<Account> accountList = new List<Account>();
        List<Contact> contactList = new List<Contact>();
        map<string,Account> mapaccount = new map<string,Account>();
        //system.debug('jsonString : '+jsonString);
        
        DXF_ResponseWrapper resWrapper = new DXF_ResponseWrapper();
        DXF_ResponseWrapper.response response = new DXF_ResponseWrapper.response();
        List<DXF_ResponseWrapper.results> resultList = new List<DXF_ResponseWrapper.results>();
        
        List<DXF_LeadRequestWrapper> wRespList = (List<DXF_LeadRequestWrapper>) JSON.deserialize(jsonString, List<DXF_LeadRequestWrapper>.class);
        
        for(DXF_LeadRequestWrapper wResp: wRespList){
            
            List<Lead> checkExistingLeads =[SELECT Id, Phone, Email, MobilePhone FROM Lead WHERE((Email =: wResp.email) OR (Phone =: wResp.phone))];
            if(checkExistingLeads.isEmpty()){
                //Lead,Account,contact creation
                Lead obj = new Lead();
                Account acc = new Account();
                
                obj.LastName = wResp.lastName;
                obj.FirstName = wResp.firstName;
                obj.Email = wResp.email;
                obj.Phone = wResp.phone;
                obj.Lead_Type__c = wResp.lead_type;
                if(wResp.fly_In_Program != NULL){
                    obj.Fly_in_Program__c = wResp.fly_In_Program;
                }
                if(wResp.donotCall != NULL){
                    obj.DoNotCall = wResp.donotCall;                
                }
                if(wResp.emailOptOut != NULL){
                    obj.HasOptedOutOfEmail = wResp.emailOptOut;
                }
                obj.MobilePhone = wResp.mobile;
                obj.Lead_DB_Id__c = wResp.Lead_DB_Id;
                obj.street = wResp.street;
                obj.city = wResp.city;
                obj.state = wResp.state;
                obj.country = wResp.country;
                obj.postalCode = wResp.postalCode;
                obj.DXF_SF_Prop_ID__c = wResp.sf_Prop_Id;
                obj.DXF_SF_Unit_Id__c = wResp.sf_Unit_Id;
                obj.Description = wResp.description;
                obj.Office_ID__c = wResp.office_Id;
                obj.Portal_Lead__c = TRUE;
                leadList.add(obj);
                
                acc.Name = wResp.firstName + wResp.lastName;
                //acc.FirstName = wResp.firstName;
                acc.IsActive__c = TRUE;
                acc.Email__c = wResp.email;
                acc.Phone = wResp.phone;
                acc.officeIds__c = wResp.office_Id;
                acc.RecordTypeId = Druce_Constants.IndAccount;
                acc.Portal_Account__c = TRUE;
                if(wResp.emailOptOut != NULL){
                    acc.PersonHasOptedOutOfEmail = wResp.emailOptOut;
                }
                acc.BillingStreet = wResp.street;
                acc.BillingCity = wResp.city;
                acc.BillingState = wResp.state;
                acc.BillingCountry = wResp.country;
                acc.BillingPostalCode = wResp.postalCode;
                acc.Description = wResp.description;
                accountList.add(acc); 
                Contact Contact = new Contact();                
                Contact.FirstName = wResp.firstName;
                Contact.lastName = wResp.lastName;
                //Contact.Title = wResp.title;
                Contact.Gender__c = wResp.gender;
                Contact.Birthdate = wResp.dateOfBirth;
                Contact.Type__c = wResp.type;
                Contact.OtherPhone = wResp.homePhone;
                Contact.Phone = wResp.phone;
                Contact.MobilePhone = wResp.mobilePhone;
                Contact.Email = wResp.email;
                Contact.buildingName__c = wResp.buildingName;
                Contact.Building_Number__c = wResp.buildingNumber;
                Contact.Line_1__c = wResp.line1;
                Contact.line2__c = wResp.line2;
                Contact.Line_3__c = wResp.line3;
                Contact.RecordTypeId = Druce_Constants.Contactrecords;
                Contact.Postcode__c = wResp.postalCode;
                Contact.Country_ID__c = wResp.country;
                Contact.Portal_Contact__c = TRUE;
                contactList.add(Contact);
            }
            
            else if(checkExistingLeads.size()>0){
                //UNIT__c unit = [SELECT Name,Project_Unit_Type__r.project__c FROM UNIT__c WHERE Id =:wResp.sf_Unit_Id];
                Account ExistingAccount = [SELECT Id, Phone, Name,PersonContactid, Email__c,officeIds__c FROM Account WHERE Email__c =: wResp.email AND Phone =: wResp.phone AND officeIds__c =: wResp.office_Id];
                list<Opportunity> CheckExistingOpportunity = [SELECT AccountId ,StageName FROM Opportunity WHERE ((AccountId=:ExistingAccount.Id AND Office_ID__c =: wResp.office_Id) AND  (StageName!='Accpeted offer'  AND StageName!='Rejected Offer'))];
                
                //system.debug(ExistingAccount);
                
                if(CheckExistingOpportunity.size()>0){
                    //Opp Already exists
                    DXF_ResponseWrapper.results result = new DXF_ResponseWrapper.results();
                    
                    result.message = 'Opportunity details already exists in system.';
                    resultList.add(result);
                    
                    response.results = resultList;
                    response.Status = 'Failed';
                    response.status_code = '400';
                    resWrapper.response = response;
                    strJSON = JSON.serialize(resWrapper);
                    
                    RestContext.response.addHeader('Content-Type', 'application/json');
                    RestContext.response.responseBody = Blob.valueOf(strJSON);
                }
                else{
                    //Lead Exists Opp creation 
                    
                    UNIT__c unit = [SELECT Name,Project_Unit_Type__r.project__c FROM UNIT__c WHERE Id =:wResp.sf_Unit_Id];
                    Opportunity opp = new Opportunity();
                    if (wResp.lead_type == 'Selling' || wResp.lead_type == 'Valuation'){
                        opp.RecordTypeId =Druce_Constants.Oppourtnityselling;
                    }
                    else if (wResp.lead_type == 'Letting'){
                        opp.RecordTypeId =Druce_Constants.OppourtnityLetting;
                    }
                    else if (wResp.lead_type == 'Buying'){
                        opp.RecordTypeId =Druce_Constants.Oppourtnitybuying;
                    }
                    else if(wResp.lead_type == 'Renting'){
                        opp.RecordTypeId =Druce_Constants.Oppourtnitytenancy;
                    }
                    
                    opp.AccountId =ExistingAccount.Id; //wResp.user_Id;
                    opp.StageName = 'Indicated Interest';
                    opp.CloseDate = System.today().addDays(10);
                    opp.Office_ID__c = wResp.office_Id;
                    if(String.isNOtBlank(wResp.sf_Prop_Id)){
                        opp.Project_Id__c = wResp.sf_Prop_Id;
                    }
                    if(String.isNOtBlank(wResp.sf_Unit_Id)){
                        opp.Unit_Id__c = wResp.sf_Unit_Id;
                        opp.Unit__c = wResp.sf_Unit_Id;
                        opp.Project_Id__c = unit.Project_Unit_Type__r.project__c;
                    }
                    opp.Name = ExistingAccount.Name+' '+unit.Name;
                    Insert opp;
                    successCheck = true;
                    DXF_ResponseWrapper.results result = new DXF_ResponseWrapper.results();
                    result.salesforce_Id = opp.Id;
                    result.message = 'Opportunity Created successfully';
                    resultList.add(result);
                    response.results = resultList;
                    response.Status = 'Success';
                    response.status_code = '200';
                    
                    resWrapper.response = response;
                    strJSON = JSON.serialize(resWrapper);
                    RestContext.response.addHeader('Content-Type', 'application/json');
                    RestContext.response.responseBody = Blob.valueOf(strJSON);
                    
                    
                }
                
            }
            
        }
            
            try{
                if(leadList.size() > 0){
                    insert leadList;
                    insert accountList;
                    for(Account a : accountList){
                        if(!mapaccount.containsKey(a.Phone+'_'+a.Email__c)){
                            mapaccount.put(a.Phone+'_'+a.Email__c, a);
                        }  
                    }
                    
                    for(Contact c :contactList){
                        if(mapaccount.containsKey(c.Phone+'_'+c.Email)){
                            c.AccountId = mapaccount.get(c.Phone+'_'+c.Email).Id;
                        }
                    }
                    insert contactList;
                    Map<String, Account> mapAcc = new Map<String,Account>();
                    for(Account a : accountList){
                        mapAcc.put(a.Email__c+''+a.Phone, a);
                    }
                    
                    successCheck = true;     
                    for(Lead ld : leadList){
                        DXF_ResponseWrapper.results result = new DXF_ResponseWrapper.results();
                        result.extDB_Id = ld.Lead_DB_Id__c;
                        result.salesforce_Id = ld.Id;
                        if(mapAcc.containsKey(ld.Email+''+ld.Phone)){
                            result.userId = mapAcc.get(ld.Email+''+ld.Phone).Id;
                        }
                        result.message = 'User Created successfully';
                        resultList.add(result);
                    }                
                    
                    response.results = resultList;
                    response.Status = 'Success';
                    response.status_code = '200';
                    resWrapper.response = response;
                    strJSON = JSON.serialize(resWrapper);
                    
                    RestContext.response.addHeader('Content-Type', 'application/json');
                    RestContext.response.responseBody = Blob.valueOf(strJSON);
                }
            }
            catch(DmlException e){
                successCheck = false;
                Integer numErrors = e.getNumDml();
                String errormessage ='Error: ';
                for(Integer i=0;i<numErrors;i++) {
                    errormessage = errormessage + e.getDmlMessage(i);
                }
                
                if(errormessage.contains('Use one of these records')){
                    response.errormessage = 'Lead details already exists in system.';
                }else{
                    response.errormessage = errormessage + '; No. of Error: ' + numErrors;    
                }
                response.Status = 'Error';
                response.status_code = '400';
                resWrapper.response = response;
                strJSON = JSON.serialize(resWrapper);
                RestContext.response.addHeader('Content-Type', 'application/json');
                RestContext.response.responseBody = Blob.valueOf(strJSON);
            }
            catch(Exception e){
                successCheck = false;       
                response.errormessage = e.getMessage();
                response.Status = 'Failed';
                response.status_code = 'Err_Excep';
                resWrapper.response = response;
                strJSON = JSON.serialize(resWrapper);
                RestContext.response.addHeader('Content-Type', 'application/json');
                RestContext.response.responseBody = Blob.valueOf(strJSON);
            }
        }
        
        /**********************Monika: Lead API - Post End:**********************************/
        
        @HttpPUT
        global Static void updateLead(){
            
            String strJSON;
            RestRequest req = RestContext.request;
            RestResponse res = Restcontext.response;
            string jsonString = req.requestBody.tostring();
            system.debug('jsonString : '+jsonString);
            
            boolean successCheck;
            List<DXF_LeadRequestWrapper> wRespList = (List<DXF_LeadRequestWrapper>) JSON.deserialize(jsonString,List<DXF_LeadRequestWrapper>.class);
            
            List<Lead> leadList = new List<Lead>();
            
            for(DXF_LeadRequestWrapper wResp: wRespList){
                Lead obj = new Lead();
                obj.LastName = wResp.LastName;   
                obj.FirstName = wResp.FirstName;    
                obj.Email = wResp.Email;   
                obj.Phone = wResp.phone;
                obj.Id = wResp.Lead_SF_Id;
                // obj.Status = wResp.leadStatus;
                obj.Lead_DB_Id__c = wResp.Lead_DB_Id;
                leadList.add(obj);
            }
            DXF_ResponseWrapper resWrapper = new DXF_ResponseWrapper();
            DXF_ResponseWrapper.response response = new DXF_ResponseWrapper.response();
            List<DXF_ResponseWrapper.results> resultList = new List<DXF_ResponseWrapper.results>();
            try{
                if(leadList.size() > 0){
                    update leadList;
                    successCheck = true;
                    
                    for(Lead ld :leadList){
                        DXF_ResponseWrapper.results result = new DXF_ResponseWrapper.results();
                        result.extDB_Id = ld.Lead_DB_Id__c;
                        result.salesforce_Id = ld.Id;
                        resultList.add(result);
                    }
                    response.results = resultList;
                    response.Status = 'Success';
                    response.status_code = '200';
                    resWrapper.response = response;
                    strJSON = JSON.serialize(resWrapper);    
                    RestContext.response.addHeader('Content-Type', 'application/json');
                    RestContext.response.responseBody = Blob.valueOf(strJSON);
                }
            }
            
            catch(Exception e){
                successCheck = false;
            }
        }
        /**********************Monika: Lead API - Put End: **********************************/
        
    }