partial/force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Primary Property</label>
</RecordType>

partial/force-app/main/default/objects/Project_Unit_Type__c/Project_Unit_Type__c.object-meta.xml
<CustomObject>
    <label>Project Unit Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Unit Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project_Unit_Type__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Unit Types</relationshipLabel>
    <relationshipName>Project_Unit_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit__c/fields/Project_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Unit_Type__c</fullName>
    <label>Project Unit Type</label>
    <referenceTo>Project_Unit_Type__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit_Preference__c/Unit_Preference__c.object-meta.xml
<CustomObject>
    <label>Unit Preference</label>
    <nameField>
        <displayFormat>UTP-{00000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit_Preference__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Unit Preferences</relationshipLabel>
    <relationshipName>Unit_Preferences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit_Preference__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Unit__c.Unit_Availability__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Preferences</relationshipLabel>
    <relationshipName>Unit_Preferences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/classes/TestDataFactory.cls
@istest
public class TestDataFactory {
    
    public static Account createAccount(String name, boolean doInsert){
        Account acc = new Account();
        acc.Name = name;
        if(doInsert){
            insert acc;
        }
        return acc;
    }
    
   public static Opportunity createOpportunity(String name,String accId,Date closeDate,String stageName, boolean doInsert ){
        Opportunity opp = new Opportunity();
        opp.Name = name;
        opp.AccountId= accId;
        opp.CloseDate = closeDate;
        opp.StageName = stageName;
        if(doInsert){
            insert opp;
        }
        return opp;
       
    }
    
    public static Lead createLead(String firstname, String lastname, String status,String email, boolean doInsert){
        Lead lead = new Lead();
        lead.FirstName = firstname;
        lead.LastName = lastname;
        lead.Status = 'New';
        lead.Email = email;
        if(doInsert){
            insert lead;
        }
        return lead;
    }
    
    public static Project__c createProject(String name, boolean doInsert){
        Project__c project = new Project__c();
        project.Name = name;
        if(doInsert){
            insert project;
        }
        return project;
    }
    
    
    public static Project_Unit_Type__c createProjectUnitType(String name, String projectId, boolean doInsert){
        Project_Unit_Type__c unitType = new Project_Unit_Type__c();
        unitType.Name = name;
        unitType.Project__c = projectId;
        if(doInsert){
            insert unitType;
        }
        return unitType;
    }
    
    public static Unit__c createUnit(String name, String unitTypeId, boolean doInsert){
        Unit__c unit = new Unit__c();
        unit.Name = name;
        unit.Project_Unit_Type__c = unitTypeId;
        if(doInsert){
            insert unit;
        }
        return unit;
    }
    
    public static Unit_Preference__c createUnitPreference( String unitId,String opportunityId, boolean doInsert){
        Unit_Preference__c unitPref = new Unit_Preference__c();
        unitPref.Unit__c = unitId;
        unitPref.Opportunity__c = opportunityId;
        if(doInsert){
            insert unitPref;
        }
        return unitPref;
    }

}