partial/force-app/main/default/objects/View_Interest__c/View_Interest__c.object-meta.xml
<CustomObject>
    <label>View Interest</label>
    <nameField>
        <label>View Interest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>View Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/View_Interest__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Name__r.PersonContact.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Expected_Move_in_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Move_in_Date__c</fullName>
    <label>Expected Move in Date</label>
    <type>Date</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>Name__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/How_flexible_are_you__c.field-meta.xml
<CustomField>
    <fullName>How_flexible_are_you__c</fullName>
    <label>How flexible are you?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Notify me the similar Properties nearby</fullName>
            </value>
            <value>
                <fullName>Only show me the exact matches</fullName>
            </value>
            <value>
                <fullName>I would consider broadening my search</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Interest_Source__c.field-meta.xml
<CustomField>
    <fullName>Interest_Source__c</fullName>
    <label>Interest Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertisement</fullName>
            </value>
            <value>
                <fullName>Banker</fullName>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
            </value>
            <value>
                <fullName>External CoBroke</fullName>
            </value>
            <value>
                <fullName>External Referral</fullName>
            </value>
            <value>
                <fullName>Financial Advisor</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Marketing Event</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
            <value>
                <fullName>Walk-In</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Interest_Status__c.field-meta.xml
<CustomField>
    <fullName>Interest_Status__c</fullName>
    <label>Interest Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Needs Analysis</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Interest_Type__c.field-meta.xml
<CustomField>
    <fullName>Interest_Type__c</fullName>
    <label>Interest Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buying</fullName>
            </value>
            <value>
                <fullName>Selling</fullName>
            </value>
            <value>
                <fullName>Letting</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Valuation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>Name__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>London Lane, E8</fullName>
            </value>
            <value>
                <fullName>london</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>View Interests</relationshipLabel>
    <relationshipName>View_Interests1</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/No_of_Bedrooms__c.field-meta.xml
<CustomField>
    <fullName>No_of_Bedrooms__c</fullName>
    <label>No. of Bedrooms</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>Name__r.PersonContact.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Price_Range_Max__c.field-meta.xml
<CustomField>
    <fullName>Price_Range_Max__c</fullName>
    <label>Price Range Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Price_Range_Min__c.field-meta.xml
<CustomField>
    <fullName>Price_Range_Min__c</fullName>
    <label>Price Range Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Tenure_Details__c.field-meta.xml
<CustomField>
    <fullName>Tenure_Details__c</fullName>
    <label>Tenure Details (For how long)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Preference</fullName>
            </value>
            <value>
                <fullName>6 Months+</fullName>
            </value>
            <value>
                <fullName>Up to 6 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Would_you_like_get_Email_Alerts__c.field-meta.xml
<CustomField>
    <fullName>Would_you_like_get_Email_Alerts__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Would you like get Email Alerts?</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/classes/ViewInterestRest_API.cls
@RestResource(urlMapping='/interest/v1/*')
global class ViewInterestRest_API {
	
    @HttpPost
    global static void CreateInterest(){
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        string reqJsonString = req.requestBody.tostring();
        string respJsonString;
        List<DXF_ViewInterestWrapper> wReqList = (List<DXF_ViewInterestWrapper>) JSON.deserialize(reqJsonString, List<DXF_ViewInterestWrapper>.class);
        system.debug('Req : '+wReqList);
        
        DXF_ResponseWrapper resWrapper = new DXF_ResponseWrapper();
        DXF_ResponseWrapper.response response = new DXF_ResponseWrapper.response();
        List<DXF_ResponseWrapper.results> resultList = new List<DXF_ResponseWrapper.results>();
        List<View_Interest__c> interestList = new List<View_Interest__c>();
        
		try{
			for(DXF_ViewInterestWrapper wReq : wReqList)
            {
				View_Interest__c interest = new View_Interest__c();
				Account act = [SELECT Id,Name FROM Account where PersonEmail = :wReq.email AND Phone = :wReq.phone];
				interest.Name__c = act.Id;
				//interest.Email__c = wReq.email;
				interest.Would_you_like_get_Email_Alerts__c = wReq.emailAlertFlag;
				//interest.First_Name__c = wReq.fName;
				//interest.Last_Name__c = wReq.lName;
				interest.No_of_Bedrooms__c = wReq.bedRoom;
				//interest.Phone__c = wReq.phone;
				interest.Price_Range_Min__c = wReq.minPrice;
				interest.Price_Range_Max__c = wReq.maxPrice;
				interest.Location__c = wReq.location;
				interest.Interest_Type__c = wReq.interestType;
				interest.Description__c = wReq.description;
				interest.Expected_Move_in_Date__c = wReq.expectedMovingDate;
				interest.Name = act.Name + ' ' + wReq.location;
				interest.Interest_Source__c = 'Website';
				interest.Interest_Status__c = 'New';
				interest.How_flexible_are_you__c = wReq.matchPreference;
				interest.Tenure_Details__c = wReq.lettingDuration;
				
				interestList.add(interest);
			}
			insert interestList;
        
			for(View_Interest__c i : interestList)
			{
				DXF_ResponseWrapper.results result = new DXF_ResponseWrapper.results();
				result.salesforce_Id = i.Id;
				result.message = 'Interest Created successfully';
				resultList.add(result);
			}
			response.results = resultList;
			response.Status = 'Success';
			response.status_code = '200';
				
			resWrapper.response = response;
			respJsonString = JSON.serialize(resWrapper);
			RestContext.response.addHeader('Content-Type', 'application/json');
			RestContext.response.responseBody = Blob.valueOf(respJsonString);
		}
		catch(DmlException e){
			Integer numOfErrors = e.getNumDml();
			String errMsg = 'Error: ';
			for(Integer i = 0; i < numOfErrors; i++){
				errMsg += e.getDMLMessage(i);
			}
			response.errormessage = errMsg + '; No. of Error: ' + numOfErrors;
			response.Status = 'Error';
            response.status_code = '400';
            resWrapper.response = response;
            respJsonString = JSON.serialize(resWrapper);
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(respJsonString);
		}
		catch(Exception e){
			response.errormessage = e.getMessage();
            response.Status = 'Failed';
            response.status_code = 'Err_Excep';
            resWrapper.response = response;
            respJsonString = JSON.serialize(resWrapper);
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(respJsonString);
		}
    }
}