partial/force-app/main/default/objects/Assignment_Rule__c/Assignment_Rule__c.object-meta.xml
<CustomObject>
    <label>Assignment Rule</label>
    <nameField>
        <displayFormat>AR#{00000}</displayFormat>
        <label>Lead Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buying</fullName>
            </value>
            <value>
                <fullName>Selling</fullName>
            </value>
            <value>
                <fullName>Letting</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Buying UK</fullName>
            </value>
            <value>
                <fullName>Primary Sell UK</fullName>
            </value>
            <value>
                <fullName>Rental UK</fullName>
            </value>
            <value>
                <fullName>Secondary Sell UK</fullName>
            </value>
            <value>
                <fullName>Tenancy UK</fullName>
            </value>
            <value>
                <fullName>Instant Valuation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>View Interest</fullName>
            </value>
            <value>
                <fullName>View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CR2 6XH</fullName>
            </value>
            <value>
                <fullName>EC1A 1AA</fullName>
            </value>
            <value>
                <fullName>EC1A 1BB</fullName>
            </value>
            <value>
                <fullName>EC3N 4AB</fullName>
            </value>
            <value>
                <fullName>GU16 7HF</fullName>
            </value>
            <value>
                <fullName>IG117RN</fullName>
            </value>
            <value>
                <fullName>IG11 7RY</fullName>
            </value>
            <value>
                <fullName>L1 8JQ</fullName>
            </value>
            <value>
                <fullName>PH49</fullName>
            </value>
            <value>
                <fullName>PO16 7GZ</fullName>
            </value>
            <value>
                <fullName>SW1A 0AA</fullName>
            </value>
            <value>
                <fullName>SW1A 0PW</fullName>
            </value>
            <value>
                <fullName>SW1A 1AA</fullName>
            </value>
            <value>
                <fullName>SW1A 2AA</fullName>
            </value>
            <value>
                <fullName>SW1W 0NY</fullName>
            </value>
            <value>
                <fullName>WC2N 5DU</fullName>
            </value>
            <value>
                <fullName>YO1 7JF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Public_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Public Group</label>
    <referenceTo>Public_Group__c</referenceTo>
    <relationshipName>Opportunity_Assignment_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Public_Group__c/Public_Group__c.object-meta.xml
<CustomObject>
    <label>Public Group</label>
    <nameField>
        <label>Public Groups Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Public_Group__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Public_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/View_Interest__c.object-meta.xml
<CustomObject>
    <label>View Interest</label>
    <nameField>
        <label>View Interest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>View Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/View_Interest__c/fields/Interest_Type__c.field-meta.xml
<CustomField>
    <fullName>Interest_Type__c</fullName>
    <label>Interest Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buying</fullName>
            </value>
            <value>
                <fullName>Selling</fullName>
            </value>
            <value>
                <fullName>Letting</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Valuation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>View Interests</relationshipLabel>
    <relationshipName>View_Interests1</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/View_Interest__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <formula>Name__r.ShippingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Postal Code</label>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/classes/ViewInterestTriggerHandler.cls
public class ViewInterestTriggerHandler {
  public static void beforeInsert(List<View_Interest__c> newRecords){
        
        Set<Id> Ids = new Set<Id>();
        Map<String, List<Assignment_Rule__c>> mapAR = new Map<String, List<Assignment_Rule__c>>();
        
        for(View_Interest__c vi : newRecords){
            Ids.add(vi.Name__c);
        }
        
        Set<Id> groupIds = new Set<Id>();
        for(Assignment_Rule__c AR : [SELECT Id,Public_Group__c,Business_Type__c FROM Assignment_Rule__c WHERE Object__c = 'View Interest' AND Active__c = TRUE]){
          groupIds.add(AR.Public_Group__c);
            if(!mapAR.containsKey(AR.Business_Type__c)){                  
                mapAR.put(AR.Business_Type__c, new List<Assignment_Rule__c>{AR});
            }
        }
        
        Map<Id, Public_Group__c> mapGrp = new Map<Id, Public_Group__c>([SELECT Id,Name, Assigned_User__c FROM Public_Group__c WHERE Id IN: groupIds]);
        
        Map<Id,Account> mapAcc = new Map<Id, Account>([SELECT Id,ShippingCountry,ShippingPostalCode FROM Account WHERE Id IN: Ids]);
        
		for(View_Interest__c vi : newRecords){
            if(mapAcc.containsKey(vi.Name__c)){
                system.debug('3 ::');
                if(mapAR.containsKey(vi.Interest_Type__c)){
                    for(Assignment_Rule__c rule : mapAR.get(vi.Interest_Type__c)){
                        if(vi.Interest_Type__c == rule.Business_Type__c ){
                            if(rule.Public_Group__r.Assigned_User__c !=  NULL){
                                vi.OwnerId = rule.Public_Group__r.Assigned_User__c;
                                break;
                            }
                        }
                    }
                }
            }
        }
		
        /*for(View_Interest__c vi : newRecords){
            if(mapAcc.containsKey(vi.Name__c)){
                system.debug('1 ::');
              if(mapAcc.get(vi.Name__c).ShippingCountry == 'United Kingdom'){
                    system.debug('2 ::');
                    if(mapAR.containsKey('GB')){
                        system.debug('3 ::');
                        if(String.isNotBlank(mapAcc.get(vi.Name__c).ShippingPostalCode)){
                            system.debug('4 ::');
                          for(Assignment_Rule__c rule : mapAR.get('GB')){
                              if(vi.Interest_Type__c == rule.Business_Type__c ){
                                  if(rule.Postal_Code__c.contains(mapAcc.get(vi.Name__c).ShippingPostalCode)){
                                      if(mapGrp.containsKey(rule.Public_Group__c)){
                                          vi.OwnerId = mapGrp.get(rule.Public_Group__c).Assigned_User__c;
                                          break;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }*/
    }
}