partial/force-app/main/default/objects/Assignment_Rule__c/Assignment_Rule__c.object-meta.xml
<CustomObject>
    <label>Assignment Rule</label>
    <nameField>
        <displayFormat>AR#{00000}</displayFormat>
        <label>Lead Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buying</fullName>
            </value>
            <value>
                <fullName>Selling</fullName>
            </value>
            <value>
                <fullName>Letting</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Buying UK</fullName>
            </value>
            <value>
                <fullName>Primary Sell UK</fullName>
            </value>
            <value>
                <fullName>Rental UK</fullName>
            </value>
            <value>
                <fullName>Secondary Sell UK</fullName>
            </value>
            <value>
                <fullName>Tenancy UK</fullName>
            </value>
            <value>
                <fullName>Instant Valuation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>View Interest</fullName>
            </value>
            <value>
                <fullName>View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/OfficeId__c.field-meta.xml
<CustomField>
    <fullName>OfficeId__c</fullName>
    <label>OfficeId</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Public_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Public Group</label>
    <referenceTo>Public_Group__c</referenceTo>
    <relationshipName>Opportunity_Assignment_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Office_ID__c.field-meta.xml
<CustomField>
    <fullName>Office_ID__c</fullName>
    <label>Office ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Public_Group__c/Public_Group__c.object-meta.xml
<CustomObject>
    <label>Public Group</label>
    <nameField>
        <label>Public Groups Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Public_Group__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Public_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/classes/OpportunityAssignmentTriggerHandler.cls
public class OpportunityAssignmentTriggerHandler{
    
    public static void beforeInsert(List<Opportunity> newOpportunities){
     
        Map<Id, List<string>> officeIdMap = new Map<Id, List<string>>();
        Map<String, List<Assignment_Rule__c>> mapAR = new Map<String, List<Assignment_Rule__c>>();
        
        Set<Id> groupIds = new Set<Id>();
        for(Assignment_Rule__c AR : [SELECT Id, Public_Group__c, Public_Group__r.Assigned_User__c, Business_Type__c, OfficeId__c
                                      FROM Assignment_Rule__c 
                                      WHERE Object__c = 'Opportunity' AND Active__c = TRUE])
        {
            groupIds.add(AR.Public_Group__c);
            if(!mapAR.containsKey(AR.OfficeId__c + AR.Business_Type__c)){
                mapAR.put(AR.OfficeId__c + AR.Business_Type__c, new List<Assignment_Rule__c>{AR});
            }
        }
        
        for(Opportunity opp : newOpportunities){
            if(opp.Office_ID__c != null && opp.RecordTypeId  != null){
                
                
                if(mapAR.containsKey(opp.Office_ID__c + opp.recordtype.name ))
                 {
                    
                    for(Assignment_Rule__c rule : mapAR.get(opp.Office_ID__c + opp.recordtype.name )){
                        if(rule.Public_Group__r.Assigned_User__c != null){
                            opp.OwnerId = rule.Public_Group__r.Assigned_User__c;
                            break;
                        }
                    }
                }
            }
        }
    }
}