partial/force-app/main/default/objects/Assignment_Rule__c/Assignment_Rule__c.object-meta.xml
<CustomObject>
    <label>Assignment Rule</label>
    <nameField>
        <displayFormat>AR#{00000}</displayFormat>
        <label>Lead Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buying</fullName>
            </value>
            <value>
                <fullName>Selling</fullName>
            </value>
            <value>
                <fullName>Letting</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Buying UK</fullName>
            </value>
            <value>
                <fullName>Primary Sell UK</fullName>
            </value>
            <value>
                <fullName>Rental UK</fullName>
            </value>
            <value>
                <fullName>Secondary Sell UK</fullName>
            </value>
            <value>
                <fullName>Tenancy UK</fullName>
            </value>
            <value>
                <fullName>Instant Valuation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>View Interest</fullName>
            </value>
            <value>
                <fullName>View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CR2 6XH</fullName>
            </value>
            <value>
                <fullName>EC1A 1AA</fullName>
            </value>
            <value>
                <fullName>EC1A 1BB</fullName>
            </value>
            <value>
                <fullName>EC3N 4AB</fullName>
            </value>
            <value>
                <fullName>GU16 7HF</fullName>
            </value>
            <value>
                <fullName>IG117RN</fullName>
            </value>
            <value>
                <fullName>IG11 7RY</fullName>
            </value>
            <value>
                <fullName>L1 8JQ</fullName>
            </value>
            <value>
                <fullName>PH49</fullName>
            </value>
            <value>
                <fullName>PO16 7GZ</fullName>
            </value>
            <value>
                <fullName>SW1A 0AA</fullName>
            </value>
            <value>
                <fullName>SW1A 0PW</fullName>
            </value>
            <value>
                <fullName>SW1A 1AA</fullName>
            </value>
            <value>
                <fullName>SW1A 2AA</fullName>
            </value>
            <value>
                <fullName>SW1W 0NY</fullName>
            </value>
            <value>
                <fullName>WC2N 5DU</fullName>
            </value>
            <value>
                <fullName>YO1 7JF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Public_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Public Group</label>
    <referenceTo>Public_Group__c</referenceTo>
    <relationshipName>Opportunity_Assignment_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code old</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Public_Group__c/Public_Group__c.object-meta.xml
<CustomObject>
    <label>Public Group</label>
    <nameField>
        <label>Public Groups Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Public_Group__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Public_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Created to select Country Name in Unit Address</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Unit_Preference__c/Unit_Preference__c.object-meta.xml
<CustomObject>
    <label>Unit Preference</label>
    <nameField>
        <displayFormat>UTP-{00000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit_Preference__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Unit Preferences</relationshipLabel>
    <relationshipName>Unit_Preferences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit_Preference__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Unit__c.Unit_Availability__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Preferences</relationshipLabel>
    <relationshipName>Unit_Preferences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/classes/Druce_UnitPreferenceHandler.cls
public class Druce_UnitPreferenceHandler {
    public static void afterInsert(List<Unit_Preference__c> newRecords){
        system.debug('---->');
        Set<String> postalCodes = new Set<String>();
        Set<Id> ids = new Set<Id>();
        Map<String, List<Assignment_Rule__c>> mapAR = new Map<String, List<Assignment_Rule__c>>();
        for(Unit_Preference__c up : newRecords){          
            ids.add(up.Id);
        }
        
        Set<Id> groupIds = new Set<Id>();
        for(Assignment_Rule__c oppAR : [SELECT Id,Postal_Code__c,Public_Group__c,Public_Group__r.Assigned_User__c,Country__c,Business_Type__c FROM Assignment_Rule__c WHERE Object__c = 'Opportunity']){
            groupIds.add(oppAR.Public_Group__c);
            if(mapAR.containsKey(oppAR.Business_Type__c)){
                List<Assignment_Rule__c> lst = new List<Assignment_Rule__c>();
                lst.addAll(mapAR.get(oppAR.Business_Type__c));
                lst.add(oppAR);
                mapAR.put(oppAR.Business_Type__c, lst);     
            }else{
                mapAR.put(oppAR.Business_Type__c, new List<Assignment_Rule__c>{oppAR});
            }
        }
        
       // Map<Id, Public_Group__c> mapGrp = new Map<Id, Public_Group__c>([SELECT Id,Name, Assigned_User__c FROM Public_Group__c WHERE Id IN: groupIds]);
        List<Opportunity> lstOpportunity = new List<Opportunity>();
        
        for(Unit_Preference__c up : [SELECT Id, Unit__c, Opportunity__c, Opportunity__r.RecordType.Name, Unit__r.Unit_Address__PostalCode__s,Unit__r.Unit_Address__CountryCode__s
                                     		FROM Unit_Preference__c WHERE Id IN: Ids]){
                                         system.debug('---->');
                                                if(mapAR.containsKey(up.Opportunity__r.RecordType.Name)){
                                                    system.debug('---->');
                                                    for(Assignment_Rule__c rule : mapAR.get(up.Opportunity__r.RecordType.Name)){
                                                     	system.debug('---->');
                                                        if(rule.Public_Group__r.Assigned_User__c != NULL){
                                                            Opportunity opp = new Opportunity();
                                                            opp.Id = up.Opportunity__c;
                                                            opp.OwnerId = rule.Public_Group__r.Assigned_User__c;
                                                            lstOpportunity.add(opp);
                                                            break;  
                                                   	    }
                                                    }
                                                }
                                           /*     
                                         if(up.Unit__r.Unit_Address__CountryCode__s == 'GB'){
                                             system.debug('---->');
                                             if(mapAR.containsKey(up.Unit__r.Unit_Address__CountryCode__s)){
                                                 system.debug('---->');
                                                 for(Assignment_Rule__c rule : mapAR.get(up.Unit__r.Unit_Address__CountryCode__s)){
                                                     system.debug('---->');
                                                     if(up.Opportunity__r.RecordType.Name == rule.Business_Type__c ){
                                                         system.debug('---->');
                                                         if(rule.Postal_Code__c.contains(up.Unit__r.Unit_Address__PostalCode__s)){
                                                             Opportunity opp = new Opportunity();
                                                             opp.Id = up.Opportunity__c;
                                                             if(mapGrp.containsKey(rule.Public_Group__c)){
                                                                 if(mapGrp.get(rule.Public_Group__c).Assigned_User__c != NULL){
                                                                    opp.OwnerId = mapGrp.get(rule.Public_Group__c).Assigned_User__c;
                                                                 	lstOpportunity.add(opp);
                                                                 	break;  
                                                                 }
                                                             }
                                                         }
                                                     }
                                                 }
                                             }
                                         }else{
                                          
                                         }
*/
                                     }
        
        if(!lstOpportunity.isEmpty()){
            update lstOpportunity;
        }
        
    }
}