partial/force-app/main/default/objects/Assignment_Rule__c/Assignment_Rule__c.object-meta.xml
<CustomObject>
    <label>Assignment Rule</label>
    <nameField>
        <displayFormat>AR#{00000}</displayFormat>
        <label>Lead Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buying</fullName>
            </value>
            <value>
                <fullName>Selling</fullName>
            </value>
            <value>
                <fullName>Letting</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Buying UK</fullName>
            </value>
            <value>
                <fullName>Primary Sell UK</fullName>
            </value>
            <value>
                <fullName>Rental UK</fullName>
            </value>
            <value>
                <fullName>Secondary Sell UK</fullName>
            </value>
            <value>
                <fullName>Tenancy UK</fullName>
            </value>
            <value>
                <fullName>Instant Valuation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>View Interest</fullName>
            </value>
            <value>
                <fullName>View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CR2 6XH</fullName>
            </value>
            <value>
                <fullName>EC1A 1AA</fullName>
            </value>
            <value>
                <fullName>EC1A 1BB</fullName>
            </value>
            <value>
                <fullName>EC3N 4AB</fullName>
            </value>
            <value>
                <fullName>GU16 7HF</fullName>
            </value>
            <value>
                <fullName>IG117RN</fullName>
            </value>
            <value>
                <fullName>IG11 7RY</fullName>
            </value>
            <value>
                <fullName>L1 8JQ</fullName>
            </value>
            <value>
                <fullName>PH49</fullName>
            </value>
            <value>
                <fullName>PO16 7GZ</fullName>
            </value>
            <value>
                <fullName>SW1A 0AA</fullName>
            </value>
            <value>
                <fullName>SW1A 0PW</fullName>
            </value>
            <value>
                <fullName>SW1A 1AA</fullName>
            </value>
            <value>
                <fullName>SW1A 2AA</fullName>
            </value>
            <value>
                <fullName>SW1W 0NY</fullName>
            </value>
            <value>
                <fullName>WC2N 5DU</fullName>
            </value>
            <value>
                <fullName>YO1 7JF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Public_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Public Group</label>
    <referenceTo>Public_Group__c</referenceTo>
    <relationshipName>Opportunity_Assignment_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code old</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Public_Group__c/Public_Group__c.object-meta.xml
<CustomObject>
    <label>Public Group</label>
    <nameField>
        <label>Public Groups Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Public_Group__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Public_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit_Preference__c/Unit_Preference__c.object-meta.xml
<CustomObject>
    <label>Unit Preference</label>
    <nameField>
        <displayFormat>UTP-{00000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit_Preference__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Unit Preferences</relationshipLabel>
    <relationshipName>Unit_Preferences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit_Preference__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Unit__c.Unit_Availability__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Preferences</relationshipLabel>
    <relationshipName>Unit_Preferences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Viewing__c/Viewing__c.object-meta.xml
<CustomObject>
    <description>This Object has been created to capture the viewings details.</description>
    <label>Viewing</label>
    <nameField>
        <label>Viewing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viewings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Viewing__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Viewings</relationshipLabel>
    <relationshipName>Viewings</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/classes/ViewTriggerHandler.cls
public class ViewTriggerHandler {
  public static void beforeInsert(List<Viewing__c> newViews){
        
        Set<Id> oppids = new Set<Id>();
        Map<String, List<Assignment_Rule__c>> mapAR = new Map<String, List<Assignment_Rule__c>>();
        for(Viewing__c view : newViews){
            
            if(view.Opportunity__c != NULL){
                oppIds.add(view.Opportunity__c);
            }
        }
        
        Set<Id> groupIds = new Set<Id>();
        for(Assignment_Rule__c AR : [SELECT Id,Public_Group__c, Public_Group__r.Assigned_User__c,Business_Type__c FROM Assignment_Rule__c WHERE Object__c = 'View' AND Active__c = TRUE]){
          groupIds.add(AR.Public_Group__c);
           // groupIds.add(AR.Public_Group__c);
            if(!mapAR.containsKey(AR.Business_Type__c)){                
                mapAR.put(AR.Business_Type__c, new List<Assignment_Rule__c>{AR});
            }
        }
        
        Map<Id, Public_Group__c> mapGrp = new Map<Id, Public_Group__c>([SELECT Id,Name, Assigned_User__c FROM Public_Group__c WHERE Id IN: groupIds]);        
        
        Map<Id, Opportunity> mapOpp = new Map<Id, Opportunity>([SELECT Id,RecordType.Name,(SELECT Id,Unit__c,Unit__r.Unit_Address__CountryCode__s,Unit__r.Unit_Address__PostalCode__s FROM Unit_Preferences__r) FROM Opportunity WHERE Id IN: oppIds]);
        
        for(Viewing__c view : newViews){
            if(mapOpp.containsKey(view.Opportunity__c)){
                Opportunity op = mapOpp.get(view.Opportunity__c);
				if(op.Unit_Preferences__r.size() >0 ){
					if(mapAR.containsKey(op.RecordType.Name))
                    {
                        for(Assignment_Rule__c rule : mapAR.get(op.RecordType.Name)){
							system.debug('---->');
                        	if(op.RecordType.Name == rule.Business_Type__c ){
                            	if(rule.Public_Group__r.Assigned_User__c != NULL){
                                	view.OwnerId = rule.Public_Group__r.Assigned_User__c;
                                	break;
                            	}                            
                        	} 
                    	}
                	}
				}
               /* if(op.Unit_Preferences__r.size() >0 ){
                if(op.Unit_Preferences__r[0].Unit__r.Unit_Address__CountryCode__s == 'GB'){
                    if(mapAR.containsKey(op.Unit_Preferences__r[0].Unit__r.Unit_Address__CountryCode__s)){
                      for(Assignment_Rule__c rule : mapAR.get(op.Unit_Preferences__r[0].Unit__r.Unit_Address__CountryCode__s)){
                          system.debug('---->');
                            if(op.RecordType.Name == rule.Business_Type__c ){
                                if(rule.Postal_Code__c.contains(op.Unit_Preferences__r[0].Unit__r.Unit_Address__PostalCode__s)){                                  
                                    if(mapGrp.containsKey(rule.Public_Group__c)){
                                      if(mapGrp.get(rule.Public_Group__c).Assigned_User__c != NULL){
                                          view.OwnerId = mapGrp.get(rule.Public_Group__c).Assigned_User__c;
                                            break;  
                                         }
                                     }
                                 }
                            }
                         
                        }
                    }
                
                }
            }*/
            }
        }
        
    }
}