partial/force-app/main/default/objects/Assignment_Rule__c/Assignment_Rule__c.object-meta.xml
<CustomObject>
    <label>Assignment Rule</label>
    <nameField>
        <displayFormat>AR#{00000}</displayFormat>
        <label>Lead Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buying</fullName>
            </value>
            <value>
                <fullName>Selling</fullName>
            </value>
            <value>
                <fullName>Letting</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Buying UK</fullName>
            </value>
            <value>
                <fullName>Primary Sell UK</fullName>
            </value>
            <value>
                <fullName>Rental UK</fullName>
            </value>
            <value>
                <fullName>Secondary Sell UK</fullName>
            </value>
            <value>
                <fullName>Tenancy UK</fullName>
            </value>
            <value>
                <fullName>Instant Valuation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>View Interest</fullName>
            </value>
            <value>
                <fullName>View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/OfficeId__c.field-meta.xml
<CustomField>
    <fullName>OfficeId__c</fullName>
    <label>OfficeId</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Public_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Public Group</label>
    <referenceTo>Public_Group__c</referenceTo>
    <relationshipName>Opportunity_Assignment_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buying</fullName>
            </value>
            <value>
                <fullName>Selling</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Letting</fullName>
            </value>
            <value>
                <fullName>Valuation</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>User Registration</fullName>
            </value>
            <value>
                <fullName>Instant Valuation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Lead/fields/Office_ID__c.field-meta.xml
<CustomField>
    <fullName>Office_ID__c</fullName>
    <label>Office ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Public_Group__c/Public_Group__c.object-meta.xml
<CustomObject>
    <label>Public Group</label>
    <nameField>
        <label>Public Groups Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Public_Group__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Public_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/classes/LeadTriggerHandler.cls
public class LeadTriggerHandler {
    
    public static void beforeInsert(List<Lead> newLeads){
        
        //Set<String> postalCodes = new Set<String>();
        //Set<Id> ids = new Set<Id>();
		Map<Id, List<string>> officeIdMap = new Map<Id, List<string>>();
        Map<String, List<Assignment_Rule__c>> mapAR = new Map<String, List<Assignment_Rule__c>>();
        
        Set<Id> groupIds = new Set<Id>();
        for(Assignment_Rule__c AR : [SELECT Id,Public_Group__c,Public_Group__r.Assigned_User__c,Business_Type__c,OfficeId__c 
                                        FROM Assignment_Rule__c WHERE Object__c = 'Lead' AND Active__c = TRUE])
			{
		        groupIds.add(AR.Public_Group__c);
				if(!mapAR.containsKey(AR.OfficeId__c+AR.Business_Type__c)){
                mapAR.put(AR.OfficeId__c+AR.Business_Type__c, new List<Assignment_Rule__c>{AR});
            }
			}
			for(Lead ld : newLeads){
			   if(ld.Office_ID__c != NULL && ld.Lead_Type__c  != NULL){
			      if(mapAR.containsKey(ld.Office_ID__c+ld.Lead_Type__c)){
				    for(Assignment_Rule__c rule : mapAR.get(ld.Office_ID__c+ld.Lead_Type__c)){
					if(rule.Public_Group__r.Assigned_User__c != NULL){
                        ld.OwnerId = rule.Public_Group__r.Assigned_User__c;
                        break;
						}
					}
				}
			}
            }
    }
            }