partial/force-app/main/default/objects/Assignment_Rule__c/Assignment_Rule__c.object-meta.xml
<CustomObject>
    <label>Assignment Rule</label>
    <nameField>
        <displayFormat>AR#{00000}</displayFormat>
        <label>Lead Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buying</fullName>
            </value>
            <value>
                <fullName>Selling</fullName>
            </value>
            <value>
                <fullName>Letting</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Buying UK</fullName>
            </value>
            <value>
                <fullName>Primary Sell UK</fullName>
            </value>
            <value>
                <fullName>Rental UK</fullName>
            </value>
            <value>
                <fullName>Secondary Sell UK</fullName>
            </value>
            <value>
                <fullName>Tenancy UK</fullName>
            </value>
            <value>
                <fullName>Instant Valuation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>View Interest</fullName>
            </value>
            <value>
                <fullName>View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CR2 6XH</fullName>
            </value>
            <value>
                <fullName>EC1A 1AA</fullName>
            </value>
            <value>
                <fullName>EC1A 1BB</fullName>
            </value>
            <value>
                <fullName>EC3N 4AB</fullName>
            </value>
            <value>
                <fullName>GU16 7HF</fullName>
            </value>
            <value>
                <fullName>IG117RN</fullName>
            </value>
            <value>
                <fullName>IG11 7RY</fullName>
            </value>
            <value>
                <fullName>L1 8JQ</fullName>
            </value>
            <value>
                <fullName>PH49</fullName>
            </value>
            <value>
                <fullName>PO16 7GZ</fullName>
            </value>
            <value>
                <fullName>SW1A 0AA</fullName>
            </value>
            <value>
                <fullName>SW1A 0PW</fullName>
            </value>
            <value>
                <fullName>SW1A 1AA</fullName>
            </value>
            <value>
                <fullName>SW1A 2AA</fullName>
            </value>
            <value>
                <fullName>SW1W 0NY</fullName>
            </value>
            <value>
                <fullName>WC2N 5DU</fullName>
            </value>
            <value>
                <fullName>YO1 7JF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Assignment_Rule__c/fields/Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Public_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Public Group</label>
    <referenceTo>Public_Group__c</referenceTo>
    <relationshipName>Opportunity_Assignment_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code old</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Public_Group__c/Public_Group__c.object-meta.xml
<CustomObject>
    <label>Public Group</label>
    <nameField>
        <label>Public Groups Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Public_Group__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Public_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler {
	public static void beforeInsert(List<Opportunity> newOpps){
    	
        Map<String, List<Assignment_Rule__c>> mapAR = new Map<String, List<Assignment_Rule__c>>();
        
        Set<Id> groupIds = new Set<Id>();
        for(Assignment_Rule__c AR : [SELECT Id,Postal_Code__c,Public_Group__c,Public_Group__r.Assigned_User__c,Country__c,Business_Type__c 
                                        FROM Assignment_Rule__c WHERE Object__c = 'View' AND Active__c = TRUE]){
            groupIds.add(AR.Public_Group__c);
            /*
            if(!mapAR.containsKey(oppAR.Country__c)){                
                mapAR.put(oppAR.Country__c, new List<Assignment_Rule__c>());
            }
            mapAR.get(oppAR.Country__c).add(oppAR);*/
            if(!mapAR.containsKey(AR.Business_Type__c)){                
                mapAR.put(AR.Business_Type__c, new List<Assignment_Rule__c>());
            }
            mapAR.get(AR.Business_Type__c).add(AR);
        }
		
        for(Opportunity opp : [SELECT Id,RecordTypeId, RecordType.Name FROM Opportunity]){
            if(mapAR.containskey(opp.RecordType.Name)){
                
            }            
        }        
    }
}