partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit__c/fields/Reapit_Id__c.field-meta.xml
<CustomField>
    <fullName>Reapit_Id__c</fullName>
    <externalId>true</externalId>
    <label>Reapit Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/Unit_Path__c.field-meta.xml
<CustomField>
    <fullName>Unit_Path__c</fullName>
    <defaultValue>&quot;Interest Captured&quot;</defaultValue>
    <label>Unit Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interest Captured</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Interest Captured</label>
            </value>
            <value>
                <fullName>Basic Details</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Upload Media</fullName>
            </value>
            <value>
                <fullName>Valuation</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/classes/PropertiesBatch.cls
global class PropertiesBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
    public Database.QueryLocator start(Database.BatchableContext BC){
		string unitPath = 'Published';
        string Reapit_id ='LNH230017';
        String query = 'SELECT Id from Unit__c WHERE Reapit_Id__c != NULL AND  Reapit_Id__c = :Reapit_id AND Unit_Path__c != :unitpath';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Unit__c> unitLst) {
        system.debug('Size : '+unitLst.size());
        for(Unit__c unit : unitLst){
            Druce_SecondaryPropertyAPI.SyncProperties(new Set<String>{unit.Id});
        }
          
    }
    
    public void finish(Database.BatchableContext BC){
    }
    
}