partial/force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFF-{00000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Offer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Offer__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Offer__c/fields/Project_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Unit_Type__c</fullName>
    <formula>Unit__r.Project_Unit_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Unit Type</label>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Offer__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Offer__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Unit Project name must match Offer Project Name. Unit must also be available.</errorMessage>
        <filterItems>
            <field>Unit__c.Project_Unit_Type__r.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Availability__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project__c/fields/Project_Stage__c.field-meta.xml
<CustomField>
    <fullName>Project_Stage__c</fullName>
    <label>Project Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Project__c/fields/Secondary_Property__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Property__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Secondary Property</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Primary Property</label>
</RecordType>

partial/force-app/main/default/objects/Project_Unit_Type__c/Project_Unit_Type__c.object-meta.xml
<CustomObject>
    <label>Project Unit Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Unit Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project_Unit_Type__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Unit Types</relationshipLabel>
    <relationshipName>Project_Unit_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Transaction__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <formula>Project_Unit_Type__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/Project_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Unit_Type__c</fullName>
    <label>Project Unit Type</label>
    <referenceTo>Project_Unit_Type__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/Unit_Availability__c.field-meta.xml
<CustomField>
    <fullName>Unit_Availability__c</fullName>
    <label>Unit Availability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Unit_Preference__c/Unit_Preference__c.object-meta.xml
<CustomObject>
    <label>Unit Preference</label>
    <nameField>
        <displayFormat>UTP-{00000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit_Preference__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Unit Preferences</relationshipLabel>
    <relationshipName>Unit_Preferences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit_Preference__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Unit__c.Unit_Availability__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Preferences</relationshipLabel>
    <relationshipName>Unit_Preferences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/classes/Druce_opportunityAPITest.cls
@isTest
public class Druce_opportunityAPITest {
	@testSetup static void setup(){
        
        Account acc = TestDataFactory.createAccount('Test Account', false);        
        insert acc;
        
        Opportunity opp = TestDataFactory.createOpportunity('Test Opportunity',acc.Id,System.Today(), 'Indicated Interest', false);        
        insert opp;
        
        Project__c project = TestDataFactory.createProject('Test Project Secondary', false);
        project.Project_Stage__c = 'Construction';
        project.Secondary_Property__c = TRUE;
        insert project;
        
        Project_Unit_Type__c projectUT = TestDataFactory.createProjectUnitType('Independent Flats',project.Id, false);
        insert projectUT;
        
        Unit__c unit = TestDataFactory.createUnit('Duplex House',projectUT.Id, false);
        unit.Unit_Availability__c = 'Available';
        insert unit;
        
        Unit_Preference__c unitPreference = TestDataFactory.createUnitPreference(unit.Id,opp.Id, false);
        insert unitPreference;
        
        Offer__c offer = new Offer__c();
        offer.Unit__c = unit.Id;
        offer.Opportunity__c = opp.Id;
        offer.Project_Name__c = project.Id;
        insert offer;
        
        Transaction__c trans = new Transaction__c();
        trans.Opportunity__c = opp.Id;
        insert trans;
        
        
    }
    
    @isTest static void testgetOpportunity(){
        Set<String> setOpids = new Set<String>();
        for(Opportunity Opp  : [SELECT Id, Name, Type,RecordType.name FROM Opportunity]){
            setOpids.add(opp.Id);
        }
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator('Auth'));
        Druce_OpportunityAPI.doGetCallout();
        Druce_OpportunityAPI.doPostCallout(setOpids);
        Test.stopTest();
    }
}