partial/force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFF-{00000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Offer__c/fields/Offer_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Offer Date</label>
    <type>Date</type>
</CustomField>

partial/force-app/main/default/objects/Offer__c/fields/Offer_Price__c.field-meta.xml
<CustomField>
    <fullName>Offer_Price__c</fullName>
    <label>Offer Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

partial/force-app/main/default/objects/Offer__c/fields/Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer</fullName>
                <default>true</default>
                <label>Offer</label>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Rejected Offer</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>Accepted Offer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Offer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Offer__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Offer__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Unit Project name must match Offer Project Name. Unit must also be available.</errorMessage>
        <filterItems>
            <field>Unit__c.Project_Unit_Type__r.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Availability__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Offer__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Unit__r.Unit_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project__c/fields/Project_Id_DB__c.field-meta.xml
<CustomField>
    <fullName>Project_Id_DB__c</fullName>
    <externalId>true</externalId>
    <label>Project Id (DB)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Transaction__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>text(Project_Unit_Type__r.Unit_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Unit_Preference__c/Unit_Preference__c.object-meta.xml
<CustomObject>
    <label>Unit Preference</label>
    <nameField>
        <displayFormat>UTP-{00000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit_Preference__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Unit Preferences</relationshipLabel>
    <relationshipName>Unit_Preferences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit_Preference__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Unit__c.Unit_Availability__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Preferences</relationshipLabel>
    <relationshipName>Unit_Preferences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit_Preference__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Unit__r.Project_Unit_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/classes/Druce_OpportunityAPI.cls
public class Druce_OpportunityAPI {

      @future(callout=true)
    public static void doGetCallout(){
        
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setMethod('GET');
        request.setHeader('Content-Type', 'application/json');
        request.setEndpoint('https://dxapi.speridian.com/api/opportunity');
        
        HttpResponse response = http.send(request);
        system.debug('response: ' + response);
        system.debug('response: ' + response.getBody());
    }
    
 /**************************************Monika: Create Method for Oppotunity Listing, START, 20/01/2023 **************************/
    
    @future(callout=true)
    public static void doPostCallout(Set<String> RecId){
        
        List<Opportunity> oppList = [SELECT Id, Name, Type,RecordType.name 
                           FROM Opportunity WHERE Id IN:RecId];
        DXF_OppRequestWrapper reqList = New DXF_OppRequestWrapper();
        List<DXF_OppRequestWrapper.oppwrapper> datawrapper = New List<DXF_OppRequestWrapper.oppwrapper>();
  		List<DXF_OppRequestWrapper.unitpreferences> unitwrapList= New List<DXF_OppRequestWrapper.unitpreferences>();
        List<DXF_OppRequestWrapper.offers> offerwrapList= New List<DXF_OppRequestWrapper.offers>();
        List<DXF_OppRequestWrapper.transactions> txnwrapList= New List<DXF_OppRequestWrapper.transactions>();
        String postbody;
        for(Opportunity opp : oppList){
              DXF_OppRequestWrapper.oppwrapper req = new DXF_OppRequestWrapper.oppwrapper();
              req.Opp_Id = opp.Id;
              req.Oppt_Name = opp.Name;
            
            // Add Unit prefrences to Opportunity 
            List<Unit_Preference__c> unitList = [select name, Unit__r.name, Unit__r.Unit_Number__c, Unit_Type__c from Unit_Preference__c where Opportunity__c =: opp.Id];
            for(Unit_Preference__c units : unitList){
              DXF_OppRequestWrapper.unitpreferences upreq = new DXF_OppRequestWrapper.unitpreferences();
              upreq.UnitPrefNum = units.name;
              upreq.UnitName = units.Unit__r.name;
              upreq.Unit_Type = units.Unit_Type__c;
              unitwrapList.add(upreq);
            }
            // Add Offer to Opppotunity
              List<Offer__c > offerList = [select name, Unit__r.name, Unit__r.Unit_Number__c, Offer_Date__c, Offer_Price__c, Offer_Status__c  from Offer__c  where Opportunity__c =: opp.Id];
            for(Offer__c offers : offerList){
              DXF_OppRequestWrapper.offers offerreq = new DXF_OppRequestWrapper.offers();
              offerreq.OfferNum = offers.name;
              offerreq.UnitName = offers.Unit__r.name;
              offerreq.Offer_date = offers.Offer_Date__c;
              offerreq.Offer_price = offers.Offer_Price__c;
              offerreq.Offer_status = offers.Offer_Status__c;
              offerwrapList.add(offerreq);
            }
            // Add Transaction
            
            List<Transaction__c > txnList = [select name  from Transaction__c  where Opportunity__c =: opp.Id];
            for(Transaction__c txn : txnList){
                DXF_OppRequestWrapper.transactions txnreq = new DXF_OppRequestWrapper.transactions();
              txnreq.Name = txn.name;
              txnwrapList.add(txnreq);  
            }
            req.transactions = txnwrapList;
            req.offers = offerwrapList;
            req.unitprefs =unitwrapList;
            datawrapper.add(req);
        }   
     //   reqList.data = datawrapper;
        System.debug('request:' +  datawrapper);
        postbody = JSON.serialize(datawrapper);       
        System.debug( postbody);
       /* Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setEndpoint('https://dxapi.speridian.com/api/opportunity');
        request.setBody(postbody);
        system.debug('RequestBody: ' + postbody);
        system.debug('Request: ' + request);
        
        HttpResponse response = http.send(request);
        system.debug('response: ' + response.getBody());
        ProjectAPIResParser parsedResponse = (ProjectAPIResParser) JSON.deserialize(response.getBody(), ProjectAPIResParser.class); 
        system.debug('responseparse: ' + parsedResponse); 
        List<Project__c> resultList = new List<Project__c>();

        for( Integer i = 0; i< parsedResponse.data.size(); i++){
            Project__c obj = new Project__c();
            obj.Id = parsedResponse.data[i].Project_Id;             
            obj.Project_Id_DB__c = parsedResponse.data[i].Id;
            resultList.add(obj);
        }
        update resultList;  */
    }
    
    
}