partial/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project__c/fields/Facilities__c.field-meta.xml
<CustomField>
    <fullName>Facilities__c</fullName>
    <label>Facilities</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/fields/Planned_Handover_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Handover_Date__c</fullName>
    <label>Planned Handover Date</label>
    <type>Date</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/fields/Project_Address__c.field-meta.xml
<CustomField>
    <fullName>Project_Address__c</fullName>
    <label>Project Address</label>
    <type>Address</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/fields/Project_Id_DB__c.field-meta.xml
<CustomField>
    <fullName>Project_Id_DB__c</fullName>
    <externalId>true</externalId>
    <label>Project Id (DB)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/fields/Project_Stage__c.field-meta.xml
<CustomField>
    <fullName>Project_Stage__c</fullName>
    <label>Project Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Project__c/fields/Project_Summary__c.field-meta.xml
<CustomField>
    <fullName>Project_Summary__c</fullName>
    <label>Project Summary</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/fields/Property_Area__c.field-meta.xml
<CustomField>
    <fullName>Property_Area__c</fullName>
    <description>Size of property in meters</description>
    <label>Property Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/fields/Sponsor_Bank__c.field-meta.xml
<CustomField>
    <fullName>Sponsor_Bank__c</fullName>
    <label>Sponsor Bank</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/fields/Units_Available__c.field-meta.xml
<CustomField>
    <fullName>Units_Available__c</fullName>
    <label>Units Available</label>
    <summarizedField>Project_Unit_Type__c.No_of_Available_Units__c</summarizedField>
    <summaryForeignKey>Project_Unit_Type__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/fields/Units_Sold__c.field-meta.xml
<CustomField>
    <fullName>Units_Sold__c</fullName>
    <label>Units Sold</label>
    <summarizedField>Project_Unit_Type__c.No_of_Sold_Units__c</summarizedField>
    <summaryForeignKey>Project_Unit_Type__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/fields/UnitsAvailability__c.field-meta.xml
<CustomField>
    <fullName>UnitsAvailability__c</fullName>
    <formula>IF(
 Units_Available__c &gt; 0,
&apos;Unit Available&apos;,
IF(
 Units_Available__c = 0 &amp;&amp;  Units_Sold__c &gt; 0,
&apos;All Units Sold&apos;,
&apos;Units Not Uploaded Yet&apos;
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Units Availability</label>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Primary Property</label>
</RecordType>

partial/force-app/main/default/objects/Project_Unit_Type__c/Project_Unit_Type__c.object-meta.xml
<CustomObject>
    <label>Project Unit Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Unit Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project_Unit_Type__c/fields/No_of_Available_Units__c.field-meta.xml
<CustomField>
    <fullName>No_of_Available_Units__c</fullName>
    <label>No. of Available Units</label>
    <summaryFilterItems>
        <field>Unit__c.Unit_Availability__c</field>
        <operation>equals</operation>
        <value>Available</value>
    </summaryFilterItems>
    <summaryForeignKey>Unit__c.Project_Unit_Type__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

partial/force-app/main/default/objects/Project_Unit_Type__c/fields/No_of_Sold_Units__c.field-meta.xml
<CustomField>
    <fullName>No_of_Sold_Units__c</fullName>
    <label>No. of Sold Units</label>
    <summaryFilterItems>
        <field>Unit__c.Unit_Availability__c</field>
        <operation>equals</operation>
        <value>Sold</value>
    </summaryFilterItems>
    <summaryForeignKey>Unit__c.Project_Unit_Type__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

partial/force-app/main/default/objects/Project_Unit_Type__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Unit Types</relationshipLabel>
    <relationshipName>Project_Unit_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Project_Unit_Type__c/fields/Square_Meter_Max__c.field-meta.xml
<CustomField>
    <fullName>Square_Meter_Max__c</fullName>
    <label>Square Meter (Max)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

partial/force-app/main/default/objects/Project_Unit_Type__c/fields/Square_Meter_Min__c.field-meta.xml
<CustomField>
    <fullName>Square_Meter_Min__c</fullName>
    <label>Square Meter (Min)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

partial/force-app/main/default/objects/Project_Unit_Type__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit_Type</valueSetName>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Project_Unit_Type__c/fields/UnitsAvailability__c.field-meta.xml
<CustomField>
    <fullName>UnitsAvailability__c</fullName>
    <formula>IF(
    No_of_Available_Units__c &gt; 0, 
    &apos;Units Available&apos;,
    IF(
    No_of_Available_Units__c = 0 &amp;&amp; No_of_Sold_Units__c &gt; 0, 
    &apos;All Units Sold&apos;,
    &apos;Units Not Uploaded Yet&apos;
    )
)</formula>
    <label>Units Availability</label>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/classes/ProjectRestService.cls
@RestResource(urlMapping='/projects/*')
global class ProjectRestService {
    
    @HttpGet
    global Static List<Project__c> getProject(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String recId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        List<Project__c> projResult;
        List<Project_Unit_Type__c > unitResult;
        system.debug('recId :'+recId);
        
        if(String.isNotBlank(recId) && recId.startsWith('a06')){
            projResult = [SELECT Id, Name, Country__c, City__c, Facilities__c, Planned_Handover_Date__c, 
                      Project_Address__c,Project_Id_DB__c,Project_Stage__c,Project_Summary__c,
                      Property_Area__c,  Sponsor_Bank__c, Tags__c,
                      UnitsAvailability__c, Units_Available__c, Units_Sold__c,
                      (Select Name,Unit_Type__c,No_of_Sold_Units__c,No_of_Available_Units__c,Square_Meter_Min__c,Square_Meter_Max__c,UnitsAvailability__c from Project_Unit_Types__r )
                          FROM Project__c WHERE Id = :recId];
        }else{
            projResult = [SELECT Id, Name, Country__c, City__c, Facilities__c, Planned_Handover_Date__c, 
                      Project_Address__c,Project_Id_DB__c,Project_Stage__c,Project_Summary__c,
                      Property_Area__c, Sponsor_Bank__c, Tags__c,
                      UnitsAvailability__c, Units_Available__c, Units_Sold__c,
                          (Select Name,Unit_Type__c,No_of_Sold_Units__c,No_of_Available_Units__c,Square_Meter_Min__c,Square_Meter_Max__c,UnitsAvailability__c from Project_Unit_Types__r )
                          FROM Project__c];
        }
        
        return projResult;    
    }
    
    @HttpPost
    global Static void createProject(){
        
        String strJSON;
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        string jsonString = req.requestBody.tostring();
        system.debug('jsonString : '+jsonString);
        
        boolean successCheck;
        List<responseWrapper> wRespList = (List<responseWrapper>) JSON.deserialize(jsonString,List<responseWrapper>.class);
        
        List<Project__c> prjList = new List<Project__c>();

        for(responseWrapper wResp: wRespList)
        {
          Project__c obj = new Project__c();
          obj.Name = wResp.Project_Name;   
         // obj.Property_Type__c = wResp.Project_Type;    
         // obj.Image_URL__c = wResp.Image_URL;   
          obj.Property_Area__c = wResp.Property_Area;
          obj.Project_Id_DB__c = wResp.Project_Id;
          prjList.add(obj);
       }
    system.debug('prjList : '+prjList);
      try{
        if(prjList.size() > 0){
            Insert prjList;
            successCheck = true;
            
            DXF_ResponseWrapper resWrapper = new DXF_ResponseWrapper();
            DXF_ResponseWrapper.response response = new DXF_ResponseWrapper.response();
            List<DXF_ResponseWrapper.results> resultList = new List<DXF_ResponseWrapper.results>();
            
            
            for(Project__c prj :prjList){
                DXF_ResponseWrapper.results result = new DXF_ResponseWrapper.results();
                result.extDB_Id = prj.Project_Id_DB__c;
                result.salesforce_Id = prj.Id;
                resultList.add(result);
            }
             system.debug('resultList : '+resultList);
            response.results = resultList;
            response.Status = 'Success';
            response.status_code = '200';
            resWrapper.response = response;
            strJSON = JSON.serialize(resWrapper);
            
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(strJSON);
        }
      }

      catch(Exception e){
        successCheck = false;
      }
    }
    
     @HttpPut
    global Static void updateProject(){
        
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        string jsonString = req.requestBody.tostring();
        system.debug('jsonString : '+jsonString);
        
        boolean successCheck;
        List<responseWrapper> wRespList = (List<responseWrapper>) JSON.deserialize(jsonString,List<responseWrapper>.class);
        
        List<Project__c> prjList = new List<Project__c>();

        for(responseWrapper wResp: wRespList)
        {
        Project__c obj = new Project__c();
          obj.Name = wResp.Project_Name;   
        //  obj.Property_Type__c = wResp.Project_Type;    
         // obj.Image_URL__c = wResp.Image_URL;   
          obj.Property_Area__c = wResp.Property_Area;
          obj.Project_Id_DB__c = wResp.Project_Id;
          obj.Id= wResp.Project_SF_Id;
          prjList.add(obj);
       }

      try{
        if(prjList.size() > 0){
            update prjList;
            successCheck = true;
            String strJSON = '{"status":"Success","Status_code":200,"message":"Project updated successfully"}';
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(strJSON);
           
        }
      }

      catch(Exception e){
        successCheck = false;
      }
    }
    
    @HttpDelete
    global Static void deleteProject(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        //String recordId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        String recordId = req.params.get('ids');   
        List<String> delIds = recordId.split(',');
        Delete [SELECT Id FROM Project__c WHERE Id IN: delIds];
        String strJSON = '{"status":"Success","Status_code":200,"message":"Project deleted successfully"}';
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody = Blob.valueOf(strJSON);
    }

    global class responseWrapper{        
        global string Project_Name;        
        global string Project_Type;        
        global string Image_URL;        
        global String Property_Area;
        global String Project_Id; 
        global string Project_SF_Id = '';
    }

}