partial/force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>API#{0000000}</displayFormat>
        <label>API Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/API_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/API_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Room__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/classes/PropertiesService.cls
@RestResource(urlMapping='/properties/*')
global class PropertiesService {
	
    @HttpPost
    global Static void createProperty(){
                
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        string jsonString = req.requestBody.tostring();
        
        jsonString = jsonString.replaceAll('new','embedded');
        String responseString;
        try{
            ReapitDataWrapper wrapper = (ReapitDataWrapper)JSON.deserialize(jsonString, ReapitDataWrapper.class);            
            List<Unit__c> lstUnit = new List<Unit__c>();
            Opportunity oppLetting = new Opportunity();
            Opportunity oppSelling = new Opportunity();
            Map<String, Opportunity> mapletopp = new Map<String, Opportunity>();
            Map<String, Opportunity> mapsellopp = new Map<String, Opportunity>();
            List<Map<String, Room__c>> maproomLists = new List<Map<String, Room__c>>();
        	System.debug('Visit Id :'+wrapper.eventId);
        	
            if(wrapper.topicId == 'properties.modified' || wrapper.topicId == 'properties.created'){
                Druce_ReapitPropertyHandler.propertySync(jsonString);
            }
            else if(wrapper.topicId == 'propertyimages.created' || wrapper.topicId == 'propertyimages.modified'){
                Druce_ReapitImagesHandler.propertyImageSync(jsonString);
            }
           else if(wrapper.topicId == 'contacts.modified' || wrapper.topicId == 'contacts.created'){
                Druce_ReapitContactHandler.contactSync(jsonString);
            }
            else if(wrapper.topicId == 'vendors.modified' || wrapper.topicId == 'vendors.created'){
                Druce_ReapitVendorHandler.vendorSync(jsonString);
            }
    	}
        catch(Exception ex){
            /*system.debug('Exception : '+ex.getMessage());
            API_Log__c apiLog = new API_Log__c();
            apiLog.Method__c = 'POST';
            apiLog.Object_Name__c = 'Unit__c';        
            apiLog.Request_Body__c = jsonString;
            apiLog.Response_Body__c = responseString;
            insert apiLog; */
        }
    }
}