partial/force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>API#{0000000}</displayFormat>
        <label>API Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/API_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/API_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/classes/Druce_ReapitFilesSync.cls
@RestResource(urlMapping='/reapitFiles/*')
global class Druce_ReapitFilesSync {
	@HttpPost
    global Static void createProperty(){
                
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        string jsonString = req.requestBody.tostring();
        system.debug('jsonString : '+jsonString);
        String responseString;
        try{
            ReapitDataWrapper requestWrapper = (ReapitDataWrapper)JSON.deserialize(jsonString, ReapitDataWrapper.class);
            /*
            Druce_ReapitResponse.response response = new Druce_ReapitResponse.response();
            Druce_ReapitResponse resWrapper = new Druce_ReapitResponse();
            List<Druce_ReapitResponse.results> resultList = new List<Druce_ReapitResponse.results>();
            Druce_ReapitResponse.results result = new Druce_ReapitResponse.results();
            result.message = 'Unit successfully published into salesforce';
            resultList.add(result);
            response.results = resultList;
            response.Status = 'Success';
            response.status_code = '200';
              
        	resWrapper.response = response;
            responseString  = JSON.serialize(resWrapper);
            res.addHeader('Content-Type', 'application/json'); 
            
            res.responseBody = Blob.valueOf(responseString);*/
            
            API_Log__c apiLog = new API_Log__c();
            apiLog.Method__c = 'POST';
            apiLog.Object_Name__c = 'Unit__c';        
            apiLog.Request_Body__c = jsonString;
            apiLog.Response_Body__c = responseString;
            
            insert apiLog;
    	}
        catch(Exception ex){
            API_Log__c apiLog = new API_Log__c();
            apiLog.Method__c = 'POST';
            apiLog.Object_Name__c = 'Unit__c';        
            apiLog.Request_Body__c = jsonString;
            apiLog.Response_Body__c = responseString;
            
            insert apiLog;
        }
        
    }
    
}