partial/force-app/main/default/objects/Amazon_Files__c/Amazon_Files__c.object-meta.xml
<CustomObject>
    <label>Property Images</label>
    <nameField>
        <label>Property File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Amazon_Files__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EPC</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Floor_Plan__c.field-meta.xml
<CustomField>
    <fullName>Floor_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Floor Plan</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Reapit_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Reapit_Image_Url__c</fullName>
    <label>Reapit Image Url</label>
    <type>Url</type>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Partially Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Amazon_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>API#{0000000}</displayFormat>
        <label>API Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/API_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/API_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/Reapit_Image__c/Reapit_Image__c.object-meta.xml
<CustomObject>
    <label>Reapit File</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reapit Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Reapit_Image__c/fields/Caption__c.field-meta.xml
<CustomField>
    <fullName>Caption__c</fullName>
    <label>Caption</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Reapit_Image__c/fields/eTag__c.field-meta.xml
<CustomField>
    <fullName>eTag__c</fullName>
    <externalId>true</externalId>
    <label>eTag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Reapit_Image__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <label>Image Url</label>
    <type>Url</type>
</CustomField>

partial/force-app/main/default/objects/Reapit_Image__c/fields/Reapit_Id__c.field-meta.xml
<CustomField>
    <fullName>Reapit_Id__c</fullName>
    <externalId>true</externalId>
    <label>Reapit Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Reapit_Image__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>epc</fullName>
            </value>
            <value>
                <fullName>floorPlan</fullName>
            </value>
            <value>
                <fullName>map</fullName>
            </value>
            <value>
                <fullName>photograph</fullName>
            </value>
            <value>
                <fullName>Primary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Reapit_Image__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Reapit_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <label>EPC</label>
    <type>TextArea</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/eTag__c.field-meta.xml
<CustomField>
    <fullName>eTag__c</fullName>
    <label>eTag</label>
    <type>TextArea</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/Reapit_Id__c.field-meta.xml
<CustomField>
    <fullName>Reapit_Id__c</fullName>
    <externalId>true</externalId>
    <label>Reapit Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Bungalow</fullName>
            </value>
            <value>
                <fullName>FlatApartment</fullName>
            </value>
            <value>
                <fullName>Maisonette</fullName>
            </value>
            <value>
                <fullName>Land</fullName>
            </value>
            <value>
                <fullName>Farm</fullName>
            </value>
            <value>
                <fullName>Cottage</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
            <value>
                <fullName>DevelopmentPlot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/classes/Druce_ReapitImagesHandler.cls
public class Druce_ReapitImagesHandler {
    public static void propertyImageSync(string imageString){
        ReapitImagesWrapper requestWrapperImg = (ReapitImagesWrapper)JSON.deserialize(imageString, ReapitImagesWrapper.class); 
        
        if(requestWrapperImg.embedded != NULL){
            system.debug('--->'+requestWrapperImg.embedded);
            reapitImagesWrapper.embedded imageWrapper = requestWrapperImg.embedded;
            
            Reapit_Image__c image = new Reapit_Image__c();
            image.Caption__c = imageWrapper.caption;
            image.eTag__c = imageWrapper.eTag;
            image.Image_Url__c = imageWrapper.url;
            image.Reapit_Id__c = imageWrapper.Id;
            
            Unit__c unit = [SELECT Id, Name FROM Unit__c WHERE Reapit_Id__c =: imageWrapper.propertyId]; 
            
            image.Unit__c = unit.Id;
            system.debug('exnewVar.type ::'+imageWrapper.type);
            image.Type__c = String.valueOf(imageWrapper.type);
            image.Name = imageWrapper.id;
            upsert image Reapit_Id__c;
            
            Amazon_Files__c af = new Amazon_Files__c();
            af.Name = imageWrapper.id;
            af.Status__c = 'New';
            af.Unit__c = unit.Id;
            af.Reapit_Image_Url__c = imageWrapper.url;
            String typeImage = String.valueOf(imageWrapper.type);
            if(typeImage == 'floorPlan'){
                af.Floor_Plan__c = TRUE; 
            }
            if(typeImage == 'epc'){
                af.EPC__c = TRUE;
            }
            if(typeImage == 'Primary'){
                af.Is_Primary__c = TRUE;
            }
            upsert af;
            Druce_PublishUnitwithFiles.publishPropertiesWithFiles(new Set<String>{image.Unit__c});
            //Druce_SecondaryPropertyAPI.SyncProperties();
            API_Log__c apiLog = new API_Log__c();
            apiLog.Method__c = 'POST';
            apiLog.Object_Name__c = 'Reapit_Images__c';        
            apiLog.Request_Body__c = imageString;
           // apiLog.Response_Body__c = responseString;
            
            //insert apiLog;
            
        }        
    }
    
}