partial/force-app/main/default/objects/Amazon_Files__c/Amazon_Files__c.object-meta.xml
<CustomObject>
    <label>Property Images</label>
    <nameField>
        <label>Property File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Amazon_Files__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>jpeg</fullName>
            </value>
            <value>
                <fullName>png</fullName>
            </value>
            <value>
                <fullName>pdf</fullName>
            </value>
            <value>
                <fullName>docx</fullName>
            </value>
            <value>
                <fullName>txt</fullName>
            </value>
            <value>
                <fullName>xlsx</fullName>
            </value>
            <value>
                <fullName>csv</fullName>
            </value>
            <value>
                <fullName>mp3</fullName>
            </value>
            <value>
                <fullName>mp4</fullName>
            </value>
            <value>
                <fullName>wav</fullName>
            </value>
            <value>
                <fullName>wmv</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Partially Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Amazon_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project__c/fields/Project_Stage__c.field-meta.xml
<CustomField>
    <fullName>Project_Stage__c</fullName>
    <label>Project Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Project__c/fields/Secondary_Property__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Property__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Secondary Property</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Primary Property</label>
</RecordType>

partial/force-app/main/default/objects/Project_Unit_Type__c/Project_Unit_Type__c.object-meta.xml
<CustomObject>
    <label>Project Unit Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Unit Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project_Unit_Type__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Unit Types</relationshipLabel>
    <relationshipName>Project_Unit_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit__c/fields/Project_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Unit_Type__c</fullName>
    <label>Project Unit Type</label>
    <referenceTo>Project_Unit_Type__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/classes/AWSIntegrationTest.cls
@isTest
public class AWSIntegrationTest {
	
    @testSetup static void setup(){
        
        Project__c project = TestDataFactory.createProject('Test Project Secondary', false);
        project.Project_Stage__c = 'Construction';
        project.Secondary_Property__c = TRUE;
        insert project;
        
        Project_Unit_Type__c projectUT = TestDataFactory.createProjectUnitType('Independent Flats',project.Id, false);
        insert projectUT;
        
        Unit__c unit = TestDataFactory.createUnit('Duplex House',projectUT.Id, false);
        insert unit;
        
        Amazon_files__c amzonFile = new Amazon_files__c(Name= 'Test File', Status__c = 'New',Description__c='Test',File_Type__c= 'jpeg', Unit__c = unit.Id );       
        insert amzonFile;
        
        ContentVersion content = new ContentVersion(); 
        content.Title='Main Entrance'; 
        content.PathOnClient='/' + content.Title + '.jpg'; 
        Blob bodyBlob = Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData = bodyBlob; 
       // content.LinkedEntityId = amzonFile.id;
        content.origin = 'H';
        insert content;
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId = amzonFile.id;
        contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers';
        insert contentlink;
    }
    
    @isTest static void testUploadDocuments(){
        List<Amazon_files__c> AmazonfilesLst = [SELECT Id,Name,Status__c, Description__c FROM Amazon_files__c];
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator('Auth'));
        AWSIntegration.UploadDocuments(AmazonfilesLst,'Unit__c');
        Test.stopTest();
        
    }
}