partial/force-app/main/default/objects/Amazon_Files__c/Amazon_Files__c.object-meta.xml
<CustomObject>
    <label>Property Images</label>
    <nameField>
        <label>Property File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Amazon_Files__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EPC</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Floor_Plan__c.field-meta.xml
<CustomField>
    <fullName>Floor_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Floor Plan</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Reapit_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Reapit_Image_Url__c</fullName>
    <label>Reapit Image Url</label>
    <type>Url</type>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Partially Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Amazon_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>API#{0000000}</displayFormat>
        <label>API Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/API_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/API_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/Reapit_Image__c/Reapit_Image__c.object-meta.xml
<CustomObject>
    <label>Reapit File</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reapit Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Reapit_Image__c/fields/Caption__c.field-meta.xml
<CustomField>
    <fullName>Caption__c</fullName>
    <label>Caption</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Reapit_Image__c/fields/eTag__c.field-meta.xml
<CustomField>
    <fullName>eTag__c</fullName>
    <externalId>true</externalId>
    <label>eTag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Reapit_Image__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <label>Image Url</label>
    <type>Url</type>
</CustomField>

partial/force-app/main/default/objects/Reapit_Image__c/fields/Reapit_Id__c.field-meta.xml
<CustomField>
    <fullName>Reapit_Id__c</fullName>
    <externalId>true</externalId>
    <label>Reapit Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Reapit_Image__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>epc</fullName>
            </value>
            <value>
                <fullName>floorPlan</fullName>
            </value>
            <value>
                <fullName>map</fullName>
            </value>
            <value>
                <fullName>photograph</fullName>
            </value>
            <value>
                <fullName>Primary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Reapit_Image__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Reapit_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit__c/fields/CountOfReapitImages__c.field-meta.xml
<CustomField>
    <fullName>CountOfReapitImages__c</fullName>
    <label>CountOfReapitImages</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <label>EPC</label>
    <type>TextArea</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/eTag__c.field-meta.xml
<CustomField>
    <fullName>eTag__c</fullName>
    <label>eTag</label>
    <type>TextArea</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/Featured_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Featured_Image_Url__c</fullName>
    <label>Featured Image Url</label>
    <type>Url</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/Reapit_Id__c.field-meta.xml
<CustomField>
    <fullName>Reapit_Id__c</fullName>
    <externalId>true</externalId>
    <label>Reapit Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Bungalow</fullName>
            </value>
            <value>
                <fullName>FlatApartment</fullName>
            </value>
            <value>
                <fullName>Maisonette</fullName>
            </value>
            <value>
                <fullName>Land</fullName>
            </value>
            <value>
                <fullName>Farm</fullName>
            </value>
            <value>
                <fullName>Cottage</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
            <value>
                <fullName>DevelopmentPlot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/classes/Druce_ReapitImagesService.cls
global class Druce_ReapitImagesService implements Queueable, Database.AllowsCallouts{
    
    global Set<String> unitIds;
    global String token;
    global Integer ImageNum;
    
    public Druce_ReapitImagesService(Set<String> unitIds, String token){
        this.unitIds = unitIds;
        this.token = token;
    }
    
    public void execute(QueueableContext context) {
    	CreateImages(unitIds, token);
    }
    
    //@future(callout=true)
    public static void CreateImages(Set<String> unitIds, String token) {
        
        List<Reapit_Image__c> lstImages = new List<Reapit_Image__c>();
        List<Unit__c> unitList = New List<Unit__c>();
        Map<Id, Unit__c> UnitImgMap = New Map<Id, Unit__c>();
        try{
            for(Unit__c unit : [SELECT Id,Featured_Image_Url__c,Reapit_Id__c FROM Unit__c WHERE Reapit_Id__c IN : unitIds]){
                UnitImgMap.put(unit.Id, Unit);
                
                Http http = new Http();
                HttpRequest requestnew = new HttpRequest();
                requestnew.setMethod('GET');
                String unitId = unit.Id;
                String propId = unit.Reapit_Id__c;
                String primaryUrl = unit.Featured_Image_Url__c;
                system.debug('propId' + propId + ' ' + unitId);
                String reqpathUrl = '/propertyImages/?propertyId='+propId;
                requestnew.setEndpoint('callout:Reapit_Properties'+reqpathUrl);
                requestnew.setHeader('Content-Type','application/json');
                requestnew.setHeader('Authorization','Bearer '+token);
                requestnew.setHeader('reapit-customer', 'URA');
                requestnew.setHeader('api-version','2023-01-17');
                requestnew.setTimeout(100000);
                
                HttpResponse response = new HttpResponse();
                response = http.send(requestnew);
                system.debug('Response :: '+response);
                system.debug('Response :: '+response.getBody());
                
                string rs = response.getBody();
                //Logs
                /*API_Log__c apiLog = new API_Log__c();
                apiLog.Request_Body__c = 'Endpoint: ' + requestnew.getEndpoint() + 'Body: ' + requestnew.getBody();
                apiLog.Response_Body__c = rs;
                apiLog.Object_Name__c = 'Reapit_Image__c';
                apiLog.Method__c = 'GET';
                insert apiLog; */
                
                rs = rs.replaceAll('_embedded','embedded');
                
                if(rs!=null && response.getStatusCode() == 200){
                    Druce_ReapitImages exnew = (Druce_ReapitImages)JSON.deserialize(rs, Druce_ReapitImages.class);
                    system.debug('Images Wrapper :: '+exnew);
                    if(exnew.embedded!=null){
                        Integer ImageNum = 0;
                        //Add Primary Image
                        if(primaryUrl!= null){
                        	Reapit_Image__c primImg = new Reapit_Image__c();
                            primImg.Name = unitId + ' PimaryImage';
                            primImg.Unit__c = unitId;
                            primImg.Image_Url__c = primaryUrl;
                        	primImg.Type__c = 'Primary';
                            lstImages.add(primImg);
                        	ImageNum = 1;
                        }
                        
                        for(Druce_ReapitImages.embedded exnewVar : exnew.embedded){
                            if(primaryUrl != exnewVar.url){
                                Reapit_Image__c img = new Reapit_Image__c();
                                img.Name = unitId + ' ' +exnewVar.id;
                                img.Unit__c = unitId;
                                img.Image_Url__c = exnewVar.url;
                                img.caption__c = exnewVar.caption;
                                img.Type__c = exnewVar.type;
                                img.Order__c = exnewVar.order;
                                img.eTag__c = exnewVar.eTag;
                                lstImages.add(img);
                            }
                        }
                        
                        ImageNum = ImageNum + exnew.embedded.size();
                        if(ImageNum>0){
                        system.debug(ImageNum);
                        Unit__c unitcount = New Unit__c(Id = unitId, CountOfReapitImages__c = ImageNum);
                        unitList.add(unitcount);
                        }
                      //  update u;
                    }
                }
                else{
                    // Error Log
                }
            }
            if(!unitList.isEmpty()){
                update unitList;}
            
            if(!lstImages.isEmpty()){
                system.debug('check error');
                upsert lstImages Name;
                system.debug('check error1');
                List<Amazon_Files__c> fileLst = new List<Amazon_Files__c>();
                set<String> units = new Set<String>();
                for(Reapit_Image__c img : lstImages){
                    Amazon_Files__c af = new Amazon_Files__c();
                    af.Name = img.Name;
                    af.Status__c = 'New';
                    af.Unit__c = img.Unit__c;
                    af.Reapit_Image_Url__c = img.Image_Url__c;
                    if(img.Type__c == 'floorPlan'){
                       af.Floor_Plan__c = TRUE; 
                    }
                    if(img.Type__c == 'epc'){
                        af.EPC__c = TRUE;
                    }
                    if(img.Type__c == 'Primary'){
                        af.Is_Primary__c = TRUE;
                    }
                    units.add(af.Unit__c);
                    fileLst.add(af);
                }
                if(!fileLst.isEmpty()){
                    upsert fileLst Name;
                    system.debug('totalsize' + unitList.size());
                    system.enqueueJob(new ReapitImagesSync(unitList, unitList.size()));
                  /*  for(String strunit: units){
                      //  ReapitImagesSync.SyncReapitImages(new set<String>{strunit});
                     // system.enqueueJob(new ReapitImagesSync(new set<String>{strunit}));
                   //  Database.executeBatch(new ReapitImagesSync(new set<String>{strunit}), 1);
                   
                    }*/
                    
                }
                //AWSIntegration.SyncReapitImages(lstImages);
            }
        }
        catch(Exception e){
            system.debug('Exception: ' + e.getMessage());
        }
    }    
}