partial/force-app/main/default/objects/Amazon_Files__c/Amazon_Files__c.object-meta.xml
<CustomObject>
    <label>Property Images</label>
    <nameField>
        <label>Property File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Amazon_Files__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EPC</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Floor_Plan__c.field-meta.xml
<CustomField>
    <fullName>Floor_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Floor Plan</label>
    <type>Checkbox</type>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Path_Url__c.field-meta.xml
<CustomField>
    <fullName>Path_Url__c</fullName>
    <label>Path Url</label>
    <type>Url</type>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Project_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Id</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Amazon_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Reapit_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Reapit_Image_Url__c</fullName>
    <label>Reapit Image Url</label>
    <type>Url</type>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/S3_Response__c.field-meta.xml
<CustomField>
    <fullName>S3_Response__c</fullName>
    <description>Save S3 Response from AWSIntegration Apex Class</description>
    <label>S3 Response</label>
    <length>130768</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/S3_Response_Id__c.field-meta.xml
<CustomField>
    <fullName>S3_Response_Id__c</fullName>
    <label>S3_Response_Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Partially Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

partial/force-app/main/default/objects/Amazon_Files__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Amazon_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>API#{0000000}</displayFormat>
        <label>API Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/API_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/API_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

partial/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project_Unit_Type__c/Project_Unit_Type__c.object-meta.xml
<CustomObject>
    <label>Project Unit Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Unit Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Project_Unit_Type__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Unit Types</relationshipLabel>
    <relationshipName>Project_Unit_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/objects/Reapit_Image__c/Reapit_Image__c.object-meta.xml
<CustomObject>
    <label>Reapit File</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reapit Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Reapit_Image__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Reapit_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit__c/fields/CountAmazonFiles__c.field-meta.xml
<CustomField>
    <fullName>CountAmazonFiles__c</fullName>
    <label>CountAmazonFiles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <label>EPC</label>
    <type>TextArea</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/fields/Project_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Unit_Type__c</fullName>
    <label>Project Unit Type</label>
    <referenceTo>Project_Unit_Type__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

partial/force-app/main/default/classes/ReapitImagesSync.cls
global class ReapitImagesSync implements Queueable, Database.AllowsCallouts{ 
//global class ReapitImagesSync implements Database.Batchable<sObject>, Database.AllowsCallouts{
     
    public Set<String> unitIds;
    public List<Unit__c> lstUnits;
    public Unit__c unit;
    public Integer size;
    public Integer totalUnitSize;
    
     Public ReapitImagesSync(List<Unit__c> lstUnits, Unit__c unitdata, Integer totalSize, Integer size) {
         this.totalUnitSize = totalSize;
         this.size = size;
         this.unit = unitdata;
         this.lstUnits = lstUnits;
         system.debug('Size : '+size) ;
         system.debug('total Unit Size : '+this.totalUnitSize);
     }
    
    public ReapitImagesSync(List<Unit__c> lstUnits, Integer totalSize){
        this.totalUnitSize = totalSize;
        this.lstUnits = lstUnits;
    }
     
  /* 
     public Database.QueryLocator start(Database.BatchableContext BC){
         String query = 'Select Id from Unit__c where Id IN: unitIds';
      return Database.getQueryLocator(query);
   }
     
     public void execute(Database.BatchableContext BC, List<Unit__c> units) {
        
             SyncReapitImages(unitIds);    
     }
   public void finish(Database.BatchableContext BC){
   }*/
     public void execute(QueueableContext context) {
         if(size == NULL){
             size = 0;
         }
         system.debug('Size : '+size) ;
         system.debug('total Unit Size : '+totalUnitSize) ;
         system.debug('lstUnits : '+lstUnits) ;
         String unitId = lstUnits[size].id;
         SyncReapitImages(new Set<String>{unitId});
   //      String unitId = lstUnits[size].id;
   //      SyncReapitImages(new Set<String>{unitId});
         /*if(size < totalUnitSize){
             system.debug('debug1');
            
             if(totalUnitSize > 1){
                 system.debug('debug2') ;
            	 
                 //size = size + 1;
                 //system.enqueueJob(new ReapitImagesSync(lstUnits,lstUnits[size], totalUnitSize, size));
              	 
             }
         	 else {
                 system.debug('debug4') ;
                 String unitId = lstUnits[size].id;
                 system.debug('unitId' + unitId) ;
                 SyncReapitImages(new Set<String>{unitId});
                 system.debug('debug5') ;
              	 size = size + 1;
         }
         }*/
     }
     
    public void SyncReapitImages(Set<String> unitIds){
        system.debug('---->');
        List<Unit__c> lstUnit = [SELECT Id, Project_Unit_Type__r.Project__c,Project_Unit_Type__c,(SELECT Id,Name,Floor_Plan__c,EPC__C,Reapit_Image_Url__c,Unit__c,
                                          Unit__r.Project_Unit_Type__r.Project__c,Unit__r.Project_Unit_Type__c
                                         FROM Amazon_Files__r WHERE Unit__c IN: unitIds AND Reapit_Image_Url__c != '' AND Status__c = 'New') 
                           FROM Unit__c WHERE Id IN: unitIds];
        
        List<Amazon_Files__c> lstFiles = [SELECT Id,Name,Floor_Plan__c,EPC__C,Reapit_Image_Url__c,Unit__c,
                                          Unit__r.Project_Unit_Type__r.Project__c,Unit__r.Project_Unit_Type__c
                                         FROM Amazon_Files__c WHERE Unit__c IN: unitIds AND Reapit_Image_Url__c != ''];
        
        List<Druce_ReapitImagesWrapper> wrapperLst = new List<Druce_ReapitImagesWrapper>();
        Druce_ReapitImagesWrapper wrap = new Druce_ReapitImagesWrapper();
        List<Druce_ReapitImagesWrapper.data> wrapDataLst = new List<Druce_ReapitImagesWrapper.data>();
        
        /********************** Get Access Token *************************************************/        
        String token  = Druce_PortalAuthentication.getToken();
        for(Unit__c unit : lstUnit){
        for(Amazon_Files__c img : unit.Amazon_Files__r){            
            Druce_ReapitImagesWrapper.data wrapData = new Druce_ReapitImagesWrapper.data();
            wrapData.id = img.Id;
            wrapData.name = img.Name;
            wrapData.fileUrl = img.Reapit_Image_Url__c;            
            wrapDataLst.add(wrapData);
        }
        wrap.data = wrapDataLst;
        
        
        String postbody = JSON.serialize(wrap);       
        System.debug(postbody);
        
        String pathname = lstUnit[0].Project_Unit_Type__r.Project__c+'/'+lstUnit[0].Project_Unit_Type__c+'/'+lstUnit[0].id+'/';
        
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        // request.setHeader('Authorization', 'Bearer ' + token);
        request.setMethod('POST');
        request.setHeader('projectid', lstUnit[0].Project_Unit_Type__r.Project__c);
        request.setHeader('unitid', lstUnit[0].id);
        request.setHeader('path', pathName);
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Accept', 'application/json');
        request.setTimeout(120000);
        request.setHeader('Authorization', 'Bearer ' + token);
        request.setEndpoint('https://dxsfapi.speridian.com/api/v1/sf/fileUrlUpload');
        
        request.setBody(postbody);
        system.debug('RequestBody: ' + postbody);
        system.debug('Request: ' + request);
        
        HttpResponse response = http.send(request);
        system.debug('response: ' + response.getBody());
            if(response.getStatusCode() == 200){
            	Map<String, Object> resbody = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
                List<Object> responses = (List<Object>)resbody.get('response');
                system.debug('responses2'+ responses);
                List<Amazon_files__c> lstUpdate = new List<Amazon_files__c>();
                Integer CountAmazonFiles = 0;
                for(object objvar : responses){
                    Map<String, Object> mainresponse = (Map<String, Object>)objvar;
                    system.debug(mainresponse.size());
                    system.debug(mainresponse);
                    String S3imageId = ((object) mainresponse.get('id')).tostring();
                    String sfid = ((object) mainresponse.get('sfFileId')).tostring();
                    Map<String, Object> datastruct = (Map<String, Object>)mainresponse.get('data');
                    object path = (object) datastruct.get('path');
                    String url = path.tostring();
                    system.debug(url);
                    Amazon_files__c file = new Amazon_files__c(Path_Url__c = Url,Id=sfid,Status__c='Submitted',S3_Response__c=response.getBody(), S3_Response_Id__c = S3imageId);
                    CountAmazonFiles = CountAmazonFiles+ 1;
                	lstUpdate.add(file);
                }
                if(!lstUpdate.isEmpty()){
                    update lstUpdate;
                    unit.CountAmazonFiles__c = CountAmazonFiles;
                    system.debug('CountAmazonFiles' + CountAmazonFiles);
                    update unit;
                    system.debug('unitCountAmazonFiles' + unit.CountAmazonFiles__c);
                    size = size + 1;
                    if(totalUnitSize > size ){
                        system.debug('size  :: '+size);
                        system.debug('totalUnitSize  :: '+totalUnitSize);
                        system.debug('lstUnits  :: '+lstUnits);
                        system.debug('lstUnits Size  :: '+lstUnits[size]);
                    	system.enqueueJob(new ReapitImagesSync(lstUnits,lstUnits[size], totalUnitSize, size));
                    }
                    
                }
            }
    }
        /*        
        API_Log__c apiLog = new API_Log__c();
        apiLog.Method__c = 'POST';
        apiLog.Object_Name__c = 'Reapit_Image__c';
        apiLog.Request_Body__c = postBody;
        apiLog.Response_Body__c = response.getBody();
        insert apiLog;*/
	}

}