partial/force-app/main/default/objects/Letting__c/Letting__c.object-meta.xml
<CustomObject>
    <label>Letting</label>
    <nameField>
        <label>Letting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Letting__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Lettings</relationshipLabel>
    <relationshipName>Lettings</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Opportunity/recordTypes/Buying.recordType-meta.xml
<RecordType>
    <fullName>Buying</fullName>
    <active>true</active>
    <businessProcess>Buying Process</businessProcess>
    <label>Buying UK</label>
</RecordType>

partial/force-app/main/default/objects/Opportunity/recordTypes/Primary_UK.recordType-meta.xml
<RecordType>
    <fullName>Primary_UK</fullName>
    <active>true</active>
    <businessProcess>Selling Process</businessProcess>
    <label>Primary Sell UK</label>
</RecordType>

partial/force-app/main/default/objects/Opportunity/recordTypes/Tenancy.recordType-meta.xml
<RecordType>
    <fullName>Tenancy</fullName>
    <active>true</active>
    <businessProcess>Tenancy Process</businessProcess>
    <label>Tenancy UK</label>
</RecordType>

partial/force-app/main/default/objects/Selling__c/Selling__c.object-meta.xml
<CustomObject>
    <label>Selling</label>
    <nameField>
        <label>Selling Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Selling__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

partial/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

partial/force-app/main/default/objects/Unit__c/recordTypes/Primary_UK.recordType-meta.xml
<RecordType>
    <fullName>Primary_UK</fullName>
    <active>true</active>
    <label>Primary UK</label>
</RecordType>

partial/force-app/main/default/objects/Unit__c/recordTypes/Rental_UK.recordType-meta.xml
<RecordType>
    <fullName>Rental_UK</fullName>
    <active>false</active>
    <label>Rental UK</label>
</RecordType>

partial/force-app/main/default/objects/Unit__c/recordTypes/Secondary_UK.recordType-meta.xml
<RecordType>
    <fullName>Secondary_UK</fullName>
    <active>false</active>
    <label>Secondary UK</label>
</RecordType>

partial/force-app/main/default/classes/Druce_Constants.cls
public class Druce_Constants {
    
    public static string SALEUNIT = 'Sale';
    public static string RENTUNIT = 'Rent';
    public static string UNIT_UK = Schema.SObjectType.Unit__c.getRecordTypeInfosByName().get('UK Units').getRecordTypeId();
    public static string Unit_SG = Schema.SObjectType.Unit__c.getRecordTypeInfosByName().get('SG Units').getRecordTypeId();
    public static string UNIT_REAPIT_DATA = Schema.SObjectType.Unit__c.getRecordTypeInfosByName().get('Reapit Data').getRecordTypeId();
    public static string RENTAL_UK = Schema.SObjectType.Unit__c.getRecordTypeInfosByName().get('Rental UK').getRecordTypeId();
    public static string PRIMARY_UK = Schema.SObjectType.Unit__c.getRecordTypeInfosByName().get('Primary UK').getRecordTypeId();
	public static string SECONDARY_UK = Schema.SObjectType.Unit__c.getRecordTypeInfosByName().get('Secondary UK').getRecordTypeId();
    
    public static string AccountIndividual = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual Customer').getRecordTypeId();
    public static string IndAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual Account').getRecordTypeId();
    public static string CorpAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Corporate Customer').getRecordTypeId();
    
    public static string Contactrecords = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business Contact').getRecordTypeId();
     public static string OppourtnityValuation = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Instant Valuation').getRecordTypeId();
    public static string Oppourtnitybuying = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Buying UK').getRecordTypeId();
    public static string Oppourtnityselling = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Primary Sell UK').getRecordTypeId();
	public static string OppourtnitySecselling = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Secondary Sell UK').getRecordTypeId();
    public static string OppourtnityLetting = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Rental UK').getRecordTypeId();
    //public static string OppourtnityValuation = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Valuation').getRecordTypeId();
    public static string Oppourtnitytenancy = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Tenancy UK').getRecordTypeId();
    
    public static string Reapitletting = Schema.SObjectType.Letting__c.getRecordTypeInfosByName().get('REAPIT DATA').getRecordTypeId();
	public static string Reapitselling = Schema.SObjectType.Selling__c.getRecordTypeInfosByName().get('REAPIT DATA').getRecordTypeId();
}